<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3 . fejezet Deskriptív statisztika | Bevezetés a biostatisztikába</title>
  <meta name="description" content="Ez a jegyzet rövid bevezetést nyújt a biostatisztika alapjaiba." />
  <meta name="generator" content="bookdown 0.15 and GitBook 2.6.7" />

  <meta property="og:title" content="3 . fejezet Deskriptív statisztika | Bevezetés a biostatisztikába" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://tamas-ferenci.github.io/bevbiostat/" />
  <meta property="og:image" content="https://tamas-ferenci.github.io/bevbiostat/bevbiostatcover.png" />
  <meta property="og:description" content="Ez a jegyzet rövid bevezetést nyújt a biostatisztika alapjaiba." />
  <meta name="github-repo" content="tamas-ferenci/bevbiostat" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3 . fejezet Deskriptív statisztika | Bevezetés a biostatisztikába" />
  
  <meta name="twitter:description" content="Ez a jegyzet rövid bevezetést nyújt a biostatisztika alapjaiba." />
  <meta name="twitter:image" content="https://tamas-ferenci.github.io/bevbiostat/bevbiostatcover.png" />

<meta name="author" content="Ferenci Tamás" />


<meta name="date" content="2019-11-23" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="a-statisztika-alapjai.html"/>
<link rel="next" href="induktiv.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Ferenci Tamás<br>Bevezetés a biostatisztikába</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Előszó</a></li>
<li class="chapter" data-level="2" data-path="a-statisztika-alapjai.html"><a href="a-statisztika-alapjai.html"><i class="fa fa-check"></i><b>2</b> A statisztika alapjai</a><ul>
<li class="chapter" data-level="2.1" data-path="a-statisztika-alapjai.html"><a href="a-statisztika-alapjai.html#a-statisztika-alapfogalmai-és-ágai"><i class="fa fa-check"></i><b>2.1</b> A statisztika alapfogalmai és ágai</a></li>
<li class="chapter" data-level="2.2" data-path="a-statisztika-alapjai.html"><a href="a-statisztika-alapjai.html#alapokvaltozok"><i class="fa fa-check"></i><b>2.2</b> Változók és mérési skálák</a></li>
<li class="chapter" data-level="2.3" data-path="a-statisztika-alapjai.html"><a href="a-statisztika-alapjai.html#alapokvelhatarolas"><i class="fa fa-check"></i><b>2.3</b> A biostatisztika kapcsolódó tudományai és elhatárolása</a></li>
<li class="chapter" data-level="2.4" data-path="a-statisztika-alapjai.html"><a href="a-statisztika-alapjai.html#alapokszamtech"><i class="fa fa-check"></i><b>2.4</b> A biostatisztika számítástechnikai háttere</a></li>
<li class="chapter" data-level="2.5" data-path="a-statisztika-alapjai.html"><a href="a-statisztika-alapjai.html#alapokfutopelda"><i class="fa fa-check"></i><b>2.5</b> Futó példa</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="deskriptiv.html"><a href="deskriptiv.html"><i class="fa fa-check"></i><b>3</b> Deskriptív statisztika</a><ul>
<li class="chapter" data-level="3.1" data-path="deskriptiv.html"><a href="deskriptiv.html#deskriptivaltalaban"><i class="fa fa-check"></i><b>3.1</b> A deskriptív statisztikáról általában</a></li>
<li class="chapter" data-level="3.2" data-path="deskriptiv.html"><a href="deskriptiv.html#deskriptivcsoportositas"><i class="fa fa-check"></i><b>3.2</b> A deskriptív statisztika módszereinek csoportosításáról</a><ul>
<li class="chapter" data-level="3.2.1" data-path="deskriptiv.html"><a href="deskriptiv.html#deskriptivcsoportositasgrafanal"><i class="fa fa-check"></i><b>3.2.1</b> Grafikus és analitikus módszerek</a></li>
<li class="chapter" data-level="3.2.2" data-path="deskriptiv.html"><a href="deskriptiv.html#deskriptivcsoportositasegytobbvalt"><i class="fa fa-check"></i><b>3.2.2</b> Egy- és többváltozós módszerek</a></li>
<li class="chapter" data-level="3.2.3" data-path="deskriptiv.html"><a href="deskriptiv.html#deskriptivcsoportositasmeresiskala"><i class="fa fa-check"></i><b>3.2.3</b> A vizsgált változó(k) mérési skálája</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="deskriptiv.html"><a href="deskriptiv.html#deskriptivminegyvalt"><i class="fa fa-check"></i><b>3.3</b> Minőségi változó egyváltozós elemzése</a><ul>
<li class="chapter" data-level="3.3.1" data-path="deskriptiv.html"><a href="deskriptiv.html#deskriptivmonegyvaltanalitikus"><i class="fa fa-check"></i><b>3.3.1</b> Analitikus eszközök</a></li>
<li class="chapter" data-level="3.3.2" data-path="deskriptiv.html"><a href="deskriptiv.html#deskriptivminegyvaltgrafikus"><i class="fa fa-check"></i><b>3.3.2</b> Grafikus eszközök</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="deskriptiv.html"><a href="deskriptiv.html#deskriptivmennyegyvalt"><i class="fa fa-check"></i><b>3.4</b> Mennyiségi változó egyváltozós elemzése</a><ul>
<li class="chapter" data-level="3.4.1" data-path="deskriptiv.html"><a href="deskriptiv.html#deskriptivmennyegyvaltanalitikus"><i class="fa fa-check"></i><b>3.4.1</b> Analitikus eszközök</a></li>
<li class="chapter" data-level="3.4.2" data-path="deskriptiv.html"><a href="deskriptiv.html#deskriptivmennyegyvaltgrafikus"><i class="fa fa-check"></i><b>3.4.2</b> Grafikus eszközök</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="deskriptiv.html"><a href="deskriptiv.html#deskriptivminketvalt"><i class="fa fa-check"></i><b>3.5</b> Minőségi változók kétváltozós elemzése</a><ul>
<li class="chapter" data-level="3.5.1" data-path="deskriptiv.html"><a href="deskriptiv.html#deskriptivminketvaltanalitikus"><i class="fa fa-check"></i><b>3.5.1</b> Analitikus eszközök</a></li>
<li class="chapter" data-level="3.5.2" data-path="deskriptiv.html"><a href="deskriptiv.html#deskriptivminketvaltgrafikus"><i class="fa fa-check"></i><b>3.5.2</b> Grafikus eszközök</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="deskriptiv.html"><a href="deskriptiv.html#deskriptivmennyketvalt"><i class="fa fa-check"></i><b>3.6</b> Mennyiségi változók kétváltozós elemzése</a><ul>
<li class="chapter" data-level="3.6.1" data-path="deskriptiv.html"><a href="deskriptiv.html#deskriptivmennyketvaltanalitikus"><i class="fa fa-check"></i><b>3.6.1</b> Analitikus eszközök</a></li>
<li class="chapter" data-level="3.6.2" data-path="deskriptiv.html"><a href="deskriptiv.html#deskriptivmennyketvaltvaltgrafikus"><i class="fa fa-check"></i><b>3.6.2</b> Grafikus eszközök</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="deskriptiv.html"><a href="deskriptiv.html#deskriptivtovabbitobbvalt"><i class="fa fa-check"></i><b>3.7</b> További többváltozós elemzések</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="induktiv.html"><a href="induktiv.html"><i class="fa fa-check"></i><b>4</b> Induktív statisztika</a><ul>
<li class="chapter" data-level="4.1" data-path="induktiv.html"><a href="induktiv.html#induktivmintavetelihelyzet"><i class="fa fa-check"></i><b>4.1</b> A mintavételi helyzet és következményei</a></li>
<li class="chapter" data-level="4.2" data-path="induktiv.html"><a href="induktiv.html#induktivbecsleselmelet"><i class="fa fa-check"></i><b>4.2</b> Becsléselmélet</a></li>
<li class="chapter" data-level="4.3" data-path="induktiv.html"><a href="induktiv.html#induktivhipotezisvizsgalat"><i class="fa fa-check"></i><b>4.3</b> Hipotézisvizsgálat</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Bevezetés a biostatisztikába</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="deskriptiv" class="section level1">
<h1><span class="header-section-number">3 . fejezet</span> Deskriptív statisztika</h1>
<p>Ebben az fejezetben a statisztika <em>deskriptív</em> ágával fogunk foglalkozni. Már utaltunk rá, hogy deskriptív statisztikáról akkor beszélünk, amikor kizárólag a mintában lévő információt igyekszünk valamilyen módon megragadni (és nem törődünk azzal, hogy a minta maga is csak a valóság egy ,,szelete’’, szebben megfogalmazva: figyelmen kívül hagyjuk a mintavételi helyzetet).</p>
<p>Először ezt a gondolatot fogjuk pontosítani, közelebbről körüljárni; majd pedig megismerkedünk a leíró statisztika legalapvetőbb módszereivel. Látni fogunk grafikus és analitikus módszereket, foglalkozunk egy- és (röviden) többváltozós helyzetekkel; az ismertetést pedig a vizsgált változók mérési skálája (@ref{alapokvaltozok}. alfejezet) szerint végezzük. (Azzal, hogy a nominális és az ordinális, illetve az intervallum- és arányskálán mért változókat nem választjuk szét, hanem minőségi és mennyiségi változókról fogunk beszélni.) Ezek után az olvasó számára ismerős lesz a mai orvostudományi cikkekben alkalmazott deskriptív eszköztár túlnyomó része; az elemi eszközöknek pedig szinte egésze.</p>
<p>Ebben a fejezetben a már említett módon a Low Infant Birth Weight adatbázist fogjuk futó példaként használni a módszertani mondanivaló illusztrálására. Az ábrák és a számítások  statisztikai környezet alatt készültek.</p>
<div id="deskriptivaltalaban" class="section level2">
<h2><span class="header-section-number">3.1</span> A deskriptív statisztikáról általában</h2>
<p>Amint már többször említettük, a deskriptív statisztika definíciós jellemzője, hogy kizárólag a mintában lévő információval törődik, számára az az ,,univerzum’‘, és teljes mértékben figyelmen kívül hagyja azt a kérdéskört, hogy a mintában lévő információ hogyan viszonyul a sokaságban lévő információhoz. Innen ered a módszer neve is: a deskripció leírást jelent, azaz a deskriptív módszerek <em>pusztán</em> a minta – valamilyen szempontból ,,jó’’ – leírását célozzák meg (nem pedig következtetést a sokaságra). Nem véletlen, hogy ebben a kontextusban nagyon sokszor minta helyett  mondunk (tükrözve, hogy itt igazából nincs is jelentősége annak, hogy az adataink csak – a szó statisztikai értelmében – egy mintát jelentenek).</p>
<p>A ,,jó leírás’’ alatt legtöbbször azt értjük, hogy a mintában lévő információt úgy próbáljuk <em>tömöríteni</em>, hogy közben – valamilyen elemzési célra tekintettel – <em>kiemeljük a lényeget</em>. Erre azért van szükség, mert a legtöbb esetben a mintában lévő információ (még ha csak néhány változóra, és néhány tucat megfigyelési egységre is gondolunk) feldolgozhatatlan ,,ránézésre’‘. A számok tengeréből még a legalapvetőbb kérdésekre sem tudnánk válaszolni. Szükség van tehát olyan módszerekre, melyek ,,emészthetővé teszik’’ ezt a számtengert: csökkentik a bonyolultságát, hogy tudjuk értelmezni azt, fel tudjuk használni kérdések megválaszolásához, illetve új megállapítások eléréséhez.</p>
<p>Nyilvánvaló, hogy a bonyolultság csökkentése csak úgy lehetséges, ha információt hagyunk el. Az egész művelet kritikus pontja épp ez: annak megválasztása, hogy mennyi információt hanyagoljunk el (és persze hogyan). A ,,hogyan’’ szerepe triviális: ha egy adott, mennyiségi változóra vonatkozó 100 elemű mintából elhagyjuk az első 99 elemet, akkor ugyan egyetlen számmá, azaz teljesen áttekinthetővé alakítjuk az információt – csak épp nyilván semmit nem érünk el vele. Ha viszont kiszámoljuk az átlagot, akkor ugyanúgy egyetlen számot kapunk, de immár úgy, hogy annak van értelme, azaz felhasználhatjuk kérdések megválaszolásához, illetve új megállapítások eléréséhez.</p>
<p>A meghatározó kulcskérdés az elhanyagolásban (az információtömörítésben) tehát a ,,mennyit’’. Látható, hogy trade-off áll fenn az <em>áttekinthetőség</em>, és a <em>reprodukciós hűség</em> között: minél többet hanyagolunk el, annál inkább segítjük az áttekinthetőséget, de annál többet vesztünk az eredeti információ hűséges reprodukciójából. A deskriptív statisztika igazi sava-borsa (végeredményben a legtöbb módszer, így vagy úgy, de ebben foglal el egy álláspontot) a jó kompromisszum megkötése a kettő között. Példának okáért, adatbázisunkban a születési tömeg változó megfigyelései így néznek ki:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" title="1">birthwt<span class="op">$</span>bwt</a></code></pre></div>
<pre><code>##   [1] 2523 2551 2557 2594 2600 2622 2637 2637 2663 2665 2722 2733 2751 2750 2769
##  [16] 2769 2778 2782 2807 2821 2835 2835 2836 2863 2877 2877 2906 2920 2920 2920
##  [31] 2920 2948 2948 2977 2977 2977 2977 2922 3005 3033 3042 3062 3062 3062 3062
##  [46] 3062 3080 3090 3090 3090 3100 3104 3132 3147 3175 3175 3203 3203 3203 3225
##  [61] 3225 3232 3232 3234 3260 3274 3274 3303 3317 3317 3317 3321 3331 3374 3374
##  [76] 3402 3416 3430 3444 3459 3460 3473 3544 3487 3544 3572 3572 3586 3600 3614
##  [91] 3614 3629 3629 3637 3643 3651 3651 3651 3651 3699 3728 3756 3770 3770 3770
## [106] 3790 3799 3827 3856 3860 3860 3884 3884 3912 3940 3941 3941 3969 3983 3997
## [121] 3997 4054 4054 4111 4153 4167 4174 4238 4593 4990  709 1021 1135 1330 1474
## [136] 1588 1588 1701 1729 1790 1818 1885 1893 1899 1928 1928 1928 1936 1970 2055
## [151] 2055 2082 2084 2084 2100 2125 2126 2187 2187 2211 2225 2240 2240 2282 2296
## [166] 2296 2301 2325 2353 2353 2367 2381 2381 2381 2410 2410 2410 2414 2424 2438
## [181] 2442 2450 2466 2466 2466 2495 2495 2495 2495</code></pre>
<p>Ezt a megadást nevezhetnénk az egyik végpontnak ebben a kompromisszumban: 100% reprodukciós hűség, de – szinte – 0% áttekinthetőség. Ez a legalapvetőbb kérdések megválaszolását, a legalapvetőbb észrevételek elérését is lehetetlenné teszi.</p>
<p>Másik végpontnak vehetjük azt, amikor a fenti adatoknak csak az átlagát adjuk meg 2944.6.</p>
<p>Ez 0%-hoz közeli reprodukciós hűséget jelent (189 számból 1-et ,,gyártottunk’’, szinte semmit nem tudunk reprodukálni az eredeti adatbázisból), viszont remek az áttekinthetősége (például azonnal látható, hogy milyen érték körül csoportosulnak az adatok).</p>
<p>Az igazán érdekes az, hogy – természetszerűleg – a két végpont között számos egyéb kompromisszumot köthetünk. Megadhatjuk például (az utóbbi végponttól az előbbi felé haladva) az adatok átlagát és szórását: 2944.6 <span class="math inline">\(\pm\)</span> 729.2, az adatok átlagát, mediánját, szórását és interkvartilis terjedelmét: 2944.6 (2977) <span class="math inline">\(\pm\)</span> 729.2 (1073), vagy épp az adatok átlagát, mediánját, szórását, interkvartilis terjedelmét, illetve minimumát és maximumát: 2944.6 (2977) <span class="math inline">\(\pm\)</span> 729.2 (1073) [709-4990].</p>
<p>Látszik, hogy minden ilyen megadás egyfajta kompromisszum: egyre több információt őrzünk meg (egyre kevesebb az adatvesztés, hűségesebb a reprodukció), viszont közben romlik a megadás áttekinthetősége.</p>
<p>Összefoglalva tehát megállapíthatjuk, hogy bár az információtömörítés ugyan szükségképp adatvesztést jelent, ez azonban nem feltétlenül baj, épp ellenkezőleg: ez teszi lehetővé, hogy a fontosat észrevegyük. A kulcs a kettő közötti egyensúlyozás.</p>
</div>
<div id="deskriptivcsoportositas" class="section level2">
<h2><span class="header-section-number">3.2</span> A deskriptív statisztika módszereinek csoportosításáról</h2>
<p>Azért, hogy az igen nagy számú leíró statisztikai módszert áttekinthetően tudjuk tárgyalni, érdemes megismerkedni pár szemponttal, melyek mentén e módszerek jellegzetes, és gyakorlati szempontból fontos csoportokba sorolhatóak.</p>
<div id="deskriptivcsoportositasgrafanal" class="section level3">
<h3><span class="header-section-number">3.2.1</span> Grafikus és analitikus módszerek</h3>
<p>A fent mutatott példák (átlagtól szóráson át a terjedelemig) mind ún. <em>analitikus</em> eszközök voltak, azaz a (számszerű) információból számszerű, csak épp tömörebb, lényeget kiemelő információt gyártottak. Az analitikus módszerek tipikus példái a mutatószámok, mint amilyen az átlag vagy a szórás, bár léteznek ennél komplexebb (nem egyetlen számból álló) eredményt szolgáltató analitikus eszközök is – az azonban közös pont, hogy mindegyik számszerű kimenetet ad.</p>
<p>Ezzel állnak szemben a <em>grafikus</em> módszerek, melyek a bemenő (számszerű) információból valamilyen képi megjelenítést konstruálnak. Szokás ezért az ilyet <em>adatvizualizációnak</em> is nevezni, bár ezt a megnevezést gyakran csak a komplexebb módszerekre alkalmazzák.</p>
<p>A grafikus módszerek általában kevésbé tömörek és kevésbé objektivizálhatóak (ami gond lehet, ha például összehasonlításra van szükség), de cserébe nagyon sokszor jobban értelmezhető benyomást tudnak adni a vizsgált adatbázisról. Ennek hátterében az van, hogy az emberi agy különösen alkalmas struktúrák azonosítására, vizsgálatára grafikus információkban; így ha ügyesen tudjuk vizualizálni adatbázisunk tartalmát, azzal nagyban megkönnyíthetjük az elemzését. Nem véletlen, hogy John Wilder Tukey egyszer azt mondta: ``There is no excuse for failing to plot and look!’’ (,,Nincs mentség arra, ha nem ábrázoljuk az adatokat és nézünk egyszerűen rá!’’).</p>
</div>
<div id="deskriptivcsoportositasegytobbvalt" class="section level3">
<h3><span class="header-section-number">3.2.2</span> Egy- és többváltozós módszerek</h3>
<p>Szemben azzal, amit sokan elsőre gondolnának, hogy ti. az egyváltozós módszerekkel egyetlen változót vizsgálunk (míg a többváltozósakkal többet), valójában <strong>egyváltozós</strong> módszerekkel is vizsgálhatunk akárhány változót. A különbség tehát nem ez, hanem az, hogy az egyváltozós módszerekkel <em>egy időben</em> egyetlen változót vizsgálunk csak, míg a <strong>többváltozós</strong> módszerek egyidejűleg is több változót tekintenek. (Ha megadjuk, hogy pontosan hányat, akkor ezt az elnevezésben is szerepeltethetjük, pl. kétváltozós vizsgálat, háromváltozós vizsgálat stb.)</p>
<p>Hogy mit értünk az alatt, hogy ,,egy időben’’? Képzeljünk el egy adatbázist, melyben emberek testmagasságát és testtömegét mértük le. Okkal várjuk azt, hogy a nagyobb testmagasság tendenciájában nagyobb testtömeggel jár együtt, tehát azoknak, akiknek nagyobb a testmagasságuk, várhatóan nagyobb a testtömegük is. Igen ám, de ha   a testmagasságot vizsgáljuk, vagy  a testtömeget, akkor ezt soha nem vennénk észre! Vegyük észre, hogy bármilyen alapos elemzést is végeznénk (beleértve akár az összes megfigyelés tömörítés nélküli felsorolását), soha nem jövünk rá erre a kapcsolatra – hiszen a külön-külön végzett vizsgálatokban nem tudjuk összerendelni az ugyanazon emberhez tartozó testmagasságot és testtömeget (épp ez a definíciója a külön-külön végzésnek). Amit tehát elvesztünk, az a változók közötti  kérdésköre. Éppen ezért mondhatjuk azt, hogy egy többváltozós vizsgálat több, mint több egyváltozós vizsgálat – hiszen itt már megjelenik a változók közötti kapcsolatok kérdése is.</p>
<p>Végezetül megjegyezzük, hogy a többváltozós kategóriát néha szétbontják, arra tekintettel, hogy a többváltozós elemzés klasszikus arzenálja csak egy-két tucat változóig alkalmazható hatásosan (sőt, igazán hatásosan inkább csak 10-nél is kevesebb változóra). Az e fölötti tartományban néha megkülönböztetésül <strong>sokváltozós</strong> adatelemzésről beszélnek.</p>
</div>
<div id="deskriptivcsoportositasmeresiskala" class="section level3">
<h3><span class="header-section-number">3.2.3</span> A vizsgált változó(k) mérési skálája</h3>
<p>A leíró statisztika módszerei jellegzetesen eltérnek aszerint is, hogy milyen mérési skálán mért változó elemzéséről van szó. Amint már említettük is, az ordinális és nominális változókat nem fogjuk megkülönböztetni, és egységesen minőségi változókról fogunk beszélni, hasonlóképp az intervallum- és arányskálán mért változók esetében is egységesen mennyiségi változókról lesz szó. (A különbségekre csak utalni fogunk.)</p>
</div>
</div>
<div id="deskriptivminegyvalt" class="section level2">
<h2><span class="header-section-number">3.3</span> Minőségi változó egyváltozós elemzése</h2>
<p>Minőségi változóra jó példa adatbázisunk rassz (<code>race</code>) változója, mely az alany rassz szerinti hovatartozását adja meg és ilyen módon nominális.</p>
<div id="deskriptivmonegyvaltanalitikus" class="section level3">
<h3><span class="header-section-number">3.3.1</span> Analitikus eszközök</h3>
<p>Ilyen változó elemzésének tipikus analitikus eszköze az ún. <strong>gyakorisági sor</strong>. A gyakorisági sor a változó lehetséges kimeneteit (kategóriáit) tartalmazza, együtt azzal, hogy az adott kimenetből hány fordult elő az adatbázisban. Az ilyen ,,darabszámot’’ a statisztikában általában is <strong>gyakoriságnak</strong> nevezik, és <span class="math inline">\(f\)</span>-fel jelölik. (Illetve, ha utalni akarunk arra, hogy az <span class="math inline">\(i\)</span>-edik kategória gyakoriságáról van szó, akkor <span class="math inline">\(f_i\)</span>-vel.) Általában <span class="math inline">\(n\)</span>-nel szokás jelölni a mintanagyságot, így nyilván <span class="math inline">\(\sum_{i=1}^n f_i = n\)</span>.</p>
<p>Szokás még beszélni <strong>relatív gyakoriságról</strong> is, ami nem más, mint az előbbi (abszolút) gyakoriság osztva a mintanagysággal (azaz <span class="math inline">\(n\)</span>-nel). A relatív gyakoriság tehát azt mutatja meg, hogy egy kategóriába a megfigyelési egységek mekkora hányada esik. Nyilván <span class="math inline">\(\sum_{i=1}^n g_i = 1\)</span>.</p>
<p>Példának okáért, a rassz változó gyakorisági sora:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" title="1">birthwt<span class="op">$</span>race &lt;-<span class="st"> </span><span class="kw">factor</span>(birthwt<span class="op">$</span>race, <span class="dt">levels =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">3</span>, <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;Kaukázusi&quot;</span>, <span class="st">&quot;Afroamerikai&quot;</span>, </a>
<a class="sourceLine" id="cb5-2" title="2">    <span class="st">&quot;Egyéb&quot;</span>))</a>
<a class="sourceLine" id="cb5-3" title="3"><span class="kw">table</span>(birthwt<span class="op">$</span>race)</a></code></pre></div>
<pre><code>## 
##    Kaukázusi Afroamerikai        Egyéb 
##           96           26           67</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" title="1"><span class="kw">prop.table</span>(<span class="kw">table</span>(birthwt<span class="op">$</span>race))</a></code></pre></div>
<pre><code>## 
##    Kaukázusi Afroamerikai        Egyéb 
##          0.5          0.1          0.4</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" title="1"><span class="kw">cbind</span>(<span class="kw">table</span>(birthwt<span class="op">$</span>race), <span class="kw">prop.table</span>(<span class="kw">table</span>(birthwt<span class="op">$</span>race)))</a></code></pre></div>
<pre><code>##              [,1] [,2]
## Kaukázusi      96  0.5
## Afroamerikai   26  0.1
## Egyéb          67  0.4</code></pre>
<p>Megjegyezzük, hogy a teljes relatív gyakorisági sort a statisztikusok nagyon gyakran a változó <strong>megoszlásának</strong> hívják.</p>
<p>Vegyük észre, hogy ebben a speciális esetben az információtömörítés igazából semmilyen információveszteséggel nem járt: ez a három szám  hordoz  információt erről a változóról mint az eredeti 189 szám! Ez azonban egy abszolút speciális eset, ami kizárólag a változó minőségi mivoltának volt köszönhető.</p>
<p>A gyakorisági soron kívül egy mutatószámnak van még értelme ennél a mérési skálánál: a . A módusz (jele: <span class="math inline">\(\mathrm{Mo}\)</span>) nem más, mint a leggyakoribb kimenet (tehát az a kimenet, melyhez tartozó gyakoriság a legnagyobb az adatbázisban). Nagyon formalizálva ezt írhatnánk:
<span class="math display">\[
    \mathrm{Mo}=\mathop{\mathrm{arg\,max}}_i f_i.
\]</span></p>
<p>A példánkban tehát a rassz módusza a kaukázusi.</p>
<p>Már most megjegyezzük, hogy a módusz ún. <strong>középérték</strong>, ezen belül is helyzeti középérték; de e fogalmaknak majd a mennyiségi változóknál lesz szemléletesebb tartalma.</p>
<p>Érdemes megfigyelni, hogy itt viszont <em>már érvényesül</em> a kompromisszum a hűség és az áttekinthetőség között! Nyilván még áttekinthetőbb, ha a fenti 3 szám megadása helyett annyit mondunk, hogy ,,a módusz a kaukázusi’’, de ebben már nagyon is lesz információveszteség: nem tudhatjuk, hogy a 189-ből 189 kaukázusi vagy 64 (vagy épp 96), és semmit nem tudunk a többi kategória gyakoriságáról.</p>
<p>Végezetül megjegyezzük, hogy az ordinalitás csak annyit módosít a fentieken, hogy a gyakorisági sorban a kategóriák felsorolási sorrendje kötött lesz (nominális esetben, mint amilyen a mostani példánk is volt, nyilván érdektelen, hogy milyen sorrendben adjuk meg a kategóriákat, tetszőlegesen felcserélhettük volna a sorokat anélkül, hogy az érdemi változást okozott volna).</p>
<p>Ami a mutatószámokat illeti, ordinális esetben elvileg már definiálható lenne a medián fogalma is, de mivel használata itt nem tipikus, a bevezetését meghagyjuk későbbre.</p>
</div>
<div id="deskriptivminegyvaltgrafikus" class="section level3">
<h3><span class="header-section-number">3.3.2</span> Grafikus eszközök</h3>
<p>A minőségi változók grafikus elemzése lényegében a gyakorisági sor vizualizálását jelenti. Ennek két, gyakorlatban legtipikusabb eszköze az <strong>oszlopdiagram</strong> és a <strong>kördiagram</strong>. Az előbbi oszlopok magasságával, az utóbbi körcikkek területével szemlélteti a gyakoriságokat. (Bár ez utóbbi, jellegéből adódóan, igazából csak relatív gyakoriságokat tud szemléltetni. Oszlopdiagrammal gyakoriság és relatív gyakoriság is szemléltethető; sőt, a kettő lényegében ekvivalens, csak a függőleges tengely skálázása lesz más.)</p>
<p>Oszlopdiagramot használtunk a <a href="deskriptiv.html#fig:oszlopdiagram">3.1</a>. ábrán.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" title="1"><span class="kw">barplot</span>(<span class="kw">table</span>(birthwt<span class="op">$</span>race), <span class="dt">xlab =</span> <span class="st">&quot;Rassz&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Gyakoriság [fő]&quot;</span>)</a></code></pre></div>
<div class="figure"><span id="fig:oszlopdiagram"></span>
<img src="bevbiostat_files/figure-html/oszlopdiagram-1.png" alt="Példa egy minőségi változó ábrázolására oszlopdiagrammal." width="672" />
<p class="caption">
Figure 3.1: Példa egy minőségi változó ábrázolására oszlopdiagrammal.
</p>
</div>
<p>Az oszlop- és kördiagramok használata kapcsán megjegyzendő, hogy tudományos munkákban általában az oszlopdiagram a preferált, pszichológiai vizsgálatok szerint ugyanis az emberi szem jobban tud lineáris mértékeket kezelni és értelmezni, mint területet. Az egyetlen megfontolás, ami mégis az oszlopdiagram ellen szólhat néha, hogy az oszlopok kirajzolási sorrendje már implikál egyfajta sorrendezést (a természetes balról-jobbra olvasás miatt), ami adott esetben nem következik az változó tartalmából.</p>
<p>Az ordinalitás e téren nem sok változást okoz: az oszlopok sorrendje kötött lesz, illetve ábrázolhatóvá válik a kumulált gyakoriság is (természetesen csak oszlopdiagrammal).</p>
</div>
</div>
<div id="deskriptivmennyegyvalt" class="section level2">
<h2><span class="header-section-number">3.4</span> Mennyiségi változó egyváltozós elemzése</h2>
<p>Mennyiségi változóra jó példa adatbázisunk születési tömeg () változója, mely az alany születési tömegét adja meg (és így arányskálán mért, egész pontosan).</p>
<div id="deskriptivmennyegyvaltanalitikus" class="section level3">
<h3><span class="header-section-number">3.4.1</span> Analitikus eszközök</h3>
<p>Az analitikus eszközök közül először most is a gyakorisági sort, majd a különböző mutatószámokat tárgyaljuk meg.</p>
<div id="deskriptivmennyegyvaltanalitikusgyakorisagisor" class="section level4">
<h4><span class="header-section-number">3.4.1.1</span> Gyakorisági sor</h4>
<p>Gyakorisági sor természetesen mennyiségi változóra is készíthető, de csak módosításokkal. Annak ugyanis, hogy megszámoljuk, hogy az egyes előforduló kimenetekből mennyi van, nincs sok értelme (hogy egy példával illusztráljuk: az itt tipikus folytonos változóknál könnyen lehet, hogy minden egyes előforduló kimenetből csak egyetlen egy lesz). A problémát nyilván a folytonosság jelenti, ami ellen úgy védekezhetünk, hogy nem adott értéket felvev} megfigyelési egységek számát adjuk meg, hanem <em>adott intervallumba esőek</em> számát. Így kapjuk az <strong>osztályközös gyakorisági sort</strong>. (Az elnevezés arra utal, hogy osztályközöket hozunk létre – így fogjuk hívni az előbb említett intervallumokat.) A gyakoriság, relatív gyakoriság, kumulált gyakoriság és kumulált relatív gyakoriság értelmezése változatlan. A születési tömeg változó osztályközös gyakorisági sora (precízebben szólva: egy lehetséges osztályközös gyakorisági sora; hiszen ez már függeni fog az osztályközök megválasztásától is), a következő:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" title="1">tab &lt;-<span class="st"> </span><span class="kw">table</span>(<span class="kw">cut</span>(birthwt<span class="op">$</span>bwt, <span class="kw">seq</span>(<span class="dv">500</span>, <span class="dv">5000</span>, <span class="dv">500</span>)))</a>
<a class="sourceLine" id="cb12-2" title="2"><span class="kw">cbind</span>(<span class="dt">Ci0 =</span> <span class="kw">seq</span>(<span class="dv">500</span>, <span class="dv">4500</span>, <span class="dv">500</span>), <span class="dt">Ci1 =</span> <span class="kw">seq</span>(<span class="dv">1000</span>, <span class="dv">5000</span>, <span class="dv">500</span>), <span class="dt">fi =</span> tab, <span class="dt">gi =</span> <span class="kw">prop.table</span>(tab))</a></code></pre></div>
<pre><code>##                  Ci0  Ci1 fi    gi
## (500,1e+03]      500 1000  1 0.005
## (1e+03,1.5e+03] 1000 1500  4 0.021
## (1.5e+03,2e+03] 1500 2000 14 0.074
## (2e+03,2.5e+03] 2000 2500 40 0.212
## (2.5e+03,3e+03] 2500 3000 38 0.201
## (3e+03,3.5e+03] 3000 3500 45 0.238
## (3.5e+03,4e+03] 3500 4000 38 0.201
## (4e+03,4.5e+03] 4000 4500  7 0.037
## (4.5e+03,5e+03] 4500 5000  2 0.011</code></pre>
<p>Itt <span class="math inline">\(C_{i0}\)</span> és <span class="math inline">\(C_{i1}\)</span> az <span class="math inline">\(i\)</span>-edik osztályköz alsó és felső határát jelöli, rendre. (Az megállapodás kérdése, hogy a határon lévő megfigyelési egységeket, például egy pont 2000 grammos újszülöttet hová sorolunk, ennek természetesen csak a kerekítésből adódó diszkrétség miatt van egyáltalán jelentősége.)</p>
<p>Vegyük észre, hogy ez a megoldás lényegében azt jelenti, hogy a mennyiségi változónkat első lépésben ,,lefokozzuk’’ minőségi változóvá, és utána alkalmazzuk – mint teljesen közönséges minőségi változóra – a korábban megismert módszert.</p>
<p>Elöljáróban jegyezzük meg, hogy itt már a gyakorisági sor – szemben a minőségi esettel – igenis információvesztéssel jár: lehet 14 újszülött 1501 grammos, és lehet mind a 14 1999 grammos, mindkét esetben ugyanúgy a fenti osztályközös gyakorisági sort kapjuk. Az információvesztés mértékét nyilván az osztályközök hossza (a felosztás ,,finomsága’’) fogja meghatározni.</p>
<p>A sor előtti zárójeles megjegyzésünk már utal arra, hogy mi az osztályközös gyakorisági sorok használatának legnagyobb kihívása: az osztályközök helyes megválasztása. Az információveszteség minimalizálása szempontjából nyilván a minél szűkebb osztályközök a jobbak, viszont túlzásba ezt sem lehet vinni, különben értelmét veszti az egész eszköz, azáltal, hogy megszűnik a lényegkiemelő jelleg. (Ha egyre jobban és jobban szűkítjük az osztályközöket, akkor egy idő után visszajutunk oda, hogy az intervallumok túlnyomó részében 0 lesz a gyakoriság, a többiben pedig 1-1 – azaz lényegében visszakapjuk a minta ,,felsorolását’’.) Az egyetlen dolog, ami univerzálisan segít ezen, az a mintanagyság növelése (hiszen lehetővé teszi az osztályközök szűkítését úgy, hogy közben várhatóan nem csökken az egy osztályközbe eső megfigyelési egységek száma).</p>
<p>Ráadásul az osztópontok megválasztása nem csak az információveszteség szempontjából fontos. Az, hogy a gyakorisági sor milyen képest sugall számunkra a vizsgált változóról – sajnos – nagyban változhat akár az osztópontok nem túl lényeges áthelyezésének hatására is, különösen kis mintanagyságnál. Éppen ezért jelent a gyakorlatban komoly kihívást az osztályközök határainak jó megválasztása.</p>
<p>Hogy ezt hogyan tegyük meg, arra alapvetően két lehetőségünk van. Az egyik út az, hogy tárgyterületi információkat használunk fel, azaz megpróbálunk – az adott változó jelentését is figyelembe véve – szakmailag értelmes, tartalommal bíró osztópontokat találni. (A fenti gyakorisági sor példa erre, hiszen kerek, emberi szem számára kényelmesen értelmezhető osztópontokat vettünk fel.) A másik lehetőség, hogy tisztán statisztikai alapon (tehát a változó tárgyterületi jelentésének felhasználása nélkül) döntünk – vannak módszerek, melyek pusztán a megfigyelések statisztikai jellemzői (nagyság, szóródás stb.) alapján igyekeznek ,,kitalálni’’, hogy hová érdemes rakni az osztópontokat ahhoz, hogy a lehető leginformatívabb gyakorisági sort kapjuk. Példának okáért, az egyik ilyen ismert analitikus szabály a Sturges-szabály, ami azt javasolja, hogy <span class="math inline">\(\left\lceil \log_2 n+1\right\rceil\)</span> darab azonos szélességű osztályközt vegyünk fel a mintaminimum és -maximum között.</p>
</div>
<div id="deskriptivmennyegyvaltanalitikusmutatoszamok" class="section level4">
<h4><span class="header-section-number">3.4.1.2</span> Mutatószámok</h4>
<p>A mutatószámok a megfigyelések valamilyen jellemzőjét próbálják meg egy-egy számba tömörítve megragadni. A következőkben aszerint csoportosítva mutatjuk be őket, hogy mi ez a megragadott jellemző.</p>
<div id="deskriptivmennyegyvaltanalitikusmutatoszamokcentralistendencia" class="section level5">
<h5><span class="header-section-number">3.4.1.2.1</span> Középértékek (centrális tendencia)</h5>
<p><strong>Centrális tendencia</strong> alatt azt értjük, hogy mi az az érték, ami körül csoportosulnak a megfigyelések. Függően a konkrét mutatótól, olyanokra gondolhatunk ez alatt, mint ,,közepes’‘, ,,tipikus’’ vagy ,,átlagos’’ érték. A legtöbb statisztikai alkalmazás szempontjából ez a legfontosabb jellemzője a változónak, ezért ha csak egyetlen számmal jellemezhetjük a változót, az tipikusan a centrális tendencia valamilyen leírója lesz. Ezeket a mutatószámokat általában <strong>középértéknek</strong> vagy <strong>helyzetmutatónak</strong> nevezik.</p>
<p>A centrális tendencia legismertebb mutatója a <strong>(számtani) átlag</strong>, jele <span class="math inline">\(\overline{x}\)</span>. Definíciószerűen nem más, mint az az szám, amivel helyettesítve minden megfigyelési egység értékét, az ún. értékösszeg (a változó megfigyeléseinek összege) változatlan maradna:
<span class="math display">\[
    \overline{x}=\frac{\sum_{i=1}^n x_i}{n}.
\]</span></p>
<p>Azonnal látható, hogy ennek akkor van értelme, ha a különböző megfigyelések számtani összege valamilyen értelmes tartalommal bír. (Van például értelme beszélni egy osztály átlagos testtömegéről, hiszen a testtömegek összege értelmes kifejezés, megadja például, hogy mennyit mutatna egy mérleg, ha mindenki ráállná.) Ha azonban a változó olyan, hogy nem az megfigyelések összegének van értelme, akkor a számtani átlag használata félrevezető lehet, és mással kell helyettesíteni – például, ha a megfigyelések összege helyett azok szorzata a tárgyterületileg értelmes, akkor az ún. mértani átlaggal. (Tipikus példa erre az, ha a változó valamilyen növekedési ütemet jelent időben. Ha egy alany testtömege egy évben 1,2-szeresére nőtt, rákövetkező évben pedig 1,3-szeresére, akkor az össznövekedés nyilván nem a növekedések összege (<span class="math inline">\(1,\!2 + 1,\!2 = 2,\!4\)</span>), hanem azok szorzata (<span class="math inline">\(1,\!2 \cdot 1,\!2 = 1,\!44\)</span>) lesz.)</p>
<p>A születési tömegek átlaga 2944.6 gramm, ami azt jelenti, hogy az adatbázisban szereplő újszülöttek össz-testtömege akkor maradna változatlan, ha mindegyikük 2944.6 gramm lenne.</p>
<p>Az átlag ún. számított középérték, mivel valamilyen számszerű összefüggésben van a megfigyelések értékeivel.</p>
<p>Az átlag előnye, hogy rendkívül közismert, mindenki számára kényelmesen kezelhető, szokásos gondolkodásunkhoz közel álló mutató. (Ez olyannyira erős tényező, hogy nagyon sok orvosi publikáció még akkor is erőlteti az átlag használatát, amikor az – a mindjárt részletezendő okokból – nem célszerű.)</p>
<p>Az átlag legnagyobb hátránya, hogy nem <strong>robusztus</strong>. Egy statisztikai mutatószám robusztussága azt méri, hogy mennyire érzékeny arra, ha a mintában a többi értéktől, a csoportosulás alaptendenciájától jelentősen eltérő érték vagy értékek vannak. Az ilyen megfigyeléseket egyébként nagyon gyakran <strong>outliernek</strong> is nevezik. (,,Érzékenység’’ alatt azt értjük, hogy a mutatót mennyire tudja befolyásolni, eredeti értékétől eltéríteni ilyen outlierek jelenléte.) Az átlag ilyen szempontból extrém rossz mutató: egyrészt bármelyik megfigyelés bármilyen megváltozása módosítja az átlag értékét, de ami az igazán nagy baj, hogy ha egyetlen megfigyelés is tart a végtelenhez, úgy az átlag is tart a végtelenhez, <em>függetlenül</em> az összes többi megfigyeléstől, és függetlenül a minta nagyságától. Mindez azt mondja nekünk, hogy ha csak egyetlen outlier is van a mintában, már az is képes arra, hogy teljesen értelmetlenné tegye az átlagot. (Hiszen ha van egy ilyen outlier a mintában, akkor az átlag <em>pont hogy nem</em> a minta ,,közepes’’ értékét fogja mutatni, hanem egyre inkább az outlierét, minél jobban kilóg.)</p>
<p>Megjegyezzük, hogy pontosan emiatt az átlag használata a centrális tendencia jellemzésére nem csak gyakorlati szempontból lehet problémás (adatrögzítési hibákból, adatbázis-sérülésekből eredeti outlierek), hanem elméletileg is ellenjavallt, ha a változó olyan, hogy fel kell készülni kis számú, de a többitől lényegesen nagyobb vagy kisebb megfigyelés jelenlétére. (Ez fordulhat elő – mindenféle adatrögzítési és egyéb hiba nélkül is! – például ún. aszimmetrikus eloszlásoknál, melyekről később fogunk részletesebben beszélni.)</p>
<p>Épp ezen a robusztussági problémán igyekszik javítani a <strong>trimmelt (vagy nyesett) átlag</strong>: ezt úgy kapjuk, hogy elhagyjuk a legkisebb és legnagyobb adott számú elemet, és csak a maradékot átlagoljuk ki. Tipikusan az elhagyott megfigyelések száma alul és felül is a mintanagyság 2,5%-a; ebben az esetben 5%-os trimmelt átlagról beszélünk. (Bár elsőre ez szokatlan mutatónak tűnhet, és a tudományos irodalomban tényleg ritkábban is használják, de számos pontozásos sportágban épp ilyen elven alakítják ki a zsűri ,,átlagos’’ pontszámát.) A születési tömegek 5%-os trimmelt átlaga 2957.4 gramm, ami egyúttal azt is mutatja, lévén, hogy közel van a szokásos átlaghoz, hogy a születési tömegek aránylag szimmetrikus eloszlásúak, vélhetően komoly outlier nélkül.</p>
<p>Alapvetően más megközelítését jelenti a centrális tendencia megragadásának a <strong>medián</strong> használata, melynek jele <span class="math inline">\(\mathrm{Me}_x\)</span>. A medián nem más, mint a nagyság szerint sorbarendezett megfigyelések közül a középső. (Amennyiben a mintanagyság páros, úgy nyilván két ,,középső’’ is van, ez esetben megállapodás kérdése, hogy mit nevezünk mediánnak; vehetjük például a kettő átlagát.) Úgy is szoktak fogalmazni, hogy a medián felezőpont, az az érték, amiről elmondható, hogy alatta és felette is egyaránt ugyanannyi mintaelem (az összes fele-fele) található.</p>
<p>Értelemszerű, hogy a medián szintén a centrális tendenciát jellemzi, csak épp kevésbé megszokott módon, mint az átlag – ez egyúttal használatának egyik fő gátja is: sok ember számára a medián tartalma (és egyáltalán, értelme) kevésbé ismert, így e mutató nem annyira jól kezelhető. Előnye viszont a robusztusság, ilyen szempontból az átlaggal szemben a másik végpontot képviseli: míg az átlag extrém érzékeny volt, addig a medián extrém robusztus. A minta minden medián feletti értéke (az egyszerűség kedvéért most gondoljunk páratlan mintanagyságra) tetszőlegesen megnövelhető (akár az összes egyszerre is), vagy a medián alatti értékek tetszőlegesen lecsökkenthetőek (akár az összes egyszerre is), vagy akár a kettő együtt is, a medián értéke <em>nem változik</em>! Hátránya, hogy a jó robusztusságért cserében kevesebb információt használ fel a mintából; ezt épp a mintaértékek meglehetősen szabad ,,állítgathatósága’’ mutatja. (Hogy ez miért baj, az precízen csak induktív statisztikai keretben lehet megérteni, az ottani tárgyalás után már érthető lesz, hogy mit jelent az, hogy a medián kevésbé hatásos becslő mint az átlag.) A tanulság az, hogy ha feltehető, hogy a háttéreloszlás szimmetrikus-közeli, akkor érdemes átlagot használni, ha nem, vagy outlierek jelenlétére is fel kell készülni (azaz indokolt robusztus statisztika használata), akkor jobb a medián ilyen szempontból.</p>
<p>A születési tömegek mediánja 2977 gramm, azaz a 2977 gramm az a testtömeg, amiről elmondható, hogy az újszülöttek fele kisebb ennél, fele nagyobb.</p>
<p>Ahogy a medián a minta ,,felezőpontja’’ ugyanúgy definiálhatók általános osztópontok; ezeket <strong>kvantiliseknek</strong> nevezzük. A <span class="math inline">\(p\)</span>-kvantilis (<span class="math inline">\(0&lt;p&lt;1\)</span>) az az érték, amiről elmondható, hogy a megfigyelések <span class="math inline">\(p\)</span>-ed része kisebb nála, <span class="math inline">\(\left(1-p\right)\)</span>-ed része nagyobb nála. (Tehát a medián az <span class="math inline">\(1/2\)</span>-kvantilis.) Gyakorlati szempontból nagyobb jelentősége van még a negyedelőpontoknak, melyek neve <strong>kvartilis</strong>. Ilyenből tehát nyilván három van: a <span class="math inline">\(p=1/4,2/4=1/2,3/4\)</span>-kvantilis, ezek közül a középső persze ugyanaz mint a medián. A másik kettőt alsó és felső kvartilisnek szokták nevezni, és <span class="math inline">\(Q_1\)</span>-gyel, illetve <span class="math inline">\(Q_3\)</span>-mal jelölik. Tehát például <span class="math inline">\(Q_1\)</span> az a szám, amire igaz, hogy a minta egynegyede (darabszámra) nála kisebb értékű, háromnegyede nála nagyobb. Ezek valójában már nem is a centrális tendenciát, hanem általában az eloszlás alakját mutatják, mégpedig robusztus módon (ugyanazon okból, mint amit a mediánnál is láttunk). Ritkábban, de szokták használni ugyanerre a célra a tizedelőpontokat, nevük decilis (<span class="math inline">\(D_1,D_2,\ldots,D_9\)</span>) és a századolópontokat, nevük percentilis (<span class="math inline">\(P_1,P_2,\ldots,P_{99}\)</span>).</p>
<p>A módusz használatának a folytonosság miatt általában nincs értelme mennyiségi változó esetén, ahogy azt már említettük is. Értelmet csak az ad neki, ha diszkretizáljuk (csoportosítjuk) az adatokat, ahogy az a gyakorisági sorral történt is. Ilyenkor már van értelme móduszról beszélni, persze ekkor már csak osztályköz szintjén – szokás ezt <strong>modális osztályköznek</strong> is nevezni. Például a születési tömegek fent közölt osztályközös gyakorisági sorában (ne feledjük, itt már az is számít, hogy melyik osztályközös gyakorisági sorra vonatkozóan adjuk meg!) a modális osztályköz a 3000–3500 gramm.</p>
<p>A módusz és a medián ún. <strong>helyzeti középérték</strong>, mivel nem számítás eredményeként adódnak, hanem a többi megfigyeléshez képest elfoglalt helyzetük tünteti ki őket.</p>
<p>Ennek kapcsán azt is megjegyezzük, hogy átlagot, mediánt (és általában minden egyéb mutatószámot is) lehetséges osztályközös gyakorisági sorból (a nyers mintaelemek ismerete nélkül is) számolni, persze ekkor már csak közelítő jelleggel.</p>
</div>
<div id="deskriptivmennyegyvaltanalitikusmutatoszamokszorodas" class="section level5">
<h5><span class="header-section-number">3.4.1.2.2</span> Szóródás</h5>
<p><strong>Szóródásnak</strong> nevezzük azt, hogy a megfigyelések milyen szorosan csoportosulnak azon érték körül, ami körül csoportosulnak (lásd a centrális tendenciát!), más szóval mennyire ingadoznak a megfigyelések, mekkora változékonyság van bennük. A gyakorlatban ez a második legfontosabb kérdés: ha csak egy jellemzőt adhatunk meg, akkor az a centrális tendencia lesz, de ha kettőt, akkor megadjuk azt is, hogy mekkora a szóródás.</p>
<p>A minta szóródásának legegyszerűbb mérőszáma a legkisebb (<span class="math inline">\(\mathrm{Min}\)</span>) és a legnagyobb (<span class="math inline">\(\mathrm{Max}\)</span>) mintaelem értéke, a <strong>mintaminimum</strong> és <strong>mintamaximum</strong>, illetve kettejük különbsége, melyet <strong>terjedelemnek</strong> nevezünk és <span class="math inline">\(R\)</span>-rel jelölünk: <span class="math inline">\(R=\mathrm{Max}-\mathrm{Min}\)</span>. Ezek előnye, hogy teljesen egyértelmű a tartalmuk, hátrányuk, hogy rendkívül érzékenyek arra, hogy konkrétan milyen mintát vettünk a sokaságból, ezért következtetési célokra nem is szokták alkalmazni.</p>
<p>A születési tömegek mintaminimuma 709 gramm, mintamaximuma 4990 gramm, így e változó terjedelme 4281gramm.</p>
<p>A leggyakoribb általános célú mutatója a szóródásnak a , jele általában <span class="math inline">\(s_x\)</span> vagy <span class="math inline">\(\sigma_x\)</span>. (A kettő neve nem keverendő: a ,,szóródás’’ a jellemző, a ,,szórás’’ egy lehetséges mutatószáma a szóródásnak.) A szórás nem más, mint a megfigyelések átlagtól vett átlagos eltérése. Ez utóbbi átlag alatt négyzetes átlagot értve – egyszerű számtani átlag nem lenne jó, hiszen azzal a pozitív és negatív irányú eltérések csökkentenék (sőt, belátható, hogy kioltanák) egymás hatását. Azaz:
<span class="math display">\[
    s_x=\sqrt{\frac{\sum_{i=1}^n \left(x_i-\overline{x}\right)^2}{n}}.
\]</span></p>
<p>Ennek a négyzetét szokás szórásnégyzetnek vagy <strong>varianciának</strong> nevezni. Deskriptív esetben néha inkább mintaszórást illetve mintavarianciát mondanak (hogy a megfelelő valószínűségszámítási fogalomtól megkülönböztessék).</p>
<p>A fent definiált mutatót szokás precízen korrigálatlan mintaszórásnak nevezni, ezzel szemben a <strong>korrigált mintaszórás</strong>:
<span class="math display">\[
    s_x^{\ast}=\sqrt{\frac{\sum_{i=1}^n \left(x_i-\overline{x}\right)^2}{n-1}}.
\]</span>
A különbségük oka csak a következtető statisztikában válik világossá (a korrigálatlan mintavariancia, első ránézésre talán meglepő módon, nem torzítatlan becslője a sokasági varianciának).</p>
<p>A születési tömegek korrigált mintaszórása 729.2 gramm, tehát az újszülöttek testtömegeinek átlaguk körül vett ingadozásának (négyzetes) átlaga 729.2 gramm.</p>
<p>A szórás hátránya, hogy – az átlaghoz hasonlóan – nem robusztus mutató. (Egyrészt azért, mert maga is az eltérések négyzetét használja, ami érzékeny a kilógó értékekre, másrészt azért, mert a eltéréseket a nem-robusztus átlagtól veszi.) Egyik lehetséges megoldás az <strong>interkvartilis terjedelem</strong> (jele <span class="math inline">\(IQR\)</span>) használata, ami a felső és az alsó kvartilis különbsége:
<span class="math display">\[
    IQR=Q_3-Q_1.
\]</span>
Az interkvartilis terjedelem a robusztus kvartiliseken alapul, így robusztus mutató, és könnyen látható, hogy tartalmilag a szóródást jellemzi, hiszen minél jobban szóródott az eloszlás, annál távolabb lesz az alsó és a felső negyedelőpontja.</p>
<p>A születési tömegek interkvartilis terjedelme 1073 gramm, tehát az a tömeg, ami fölött az újszülöttek egynegyede (és alatta háromnegyede) van, 1073 grammal nagyobb annál a tömegnél, ami fölött az újszülöttek háromnegyede (és alatta egynegyede) van.</p>
<p>A másik lehetőség a szórás ,,megjavítása’‘, olyan módon, hogy az eltéréseknek nem a négyzetét, hanem az abszolút értékét vesszük. (Ezzel a kapott mennyiség matematikai kezelhetőségét rontjuk, hiszen a négyzetreemelés jobban kezelhető matematikai objektum, de a robusztusságot növeljük.) További javítási lehetőség, ha az eltéréseket nem az átlagtól hanem a mediántól vesszük, és nem is átlagoljuk őket, hanem a mediánjukat képezzük. A mutató neve, ami mindhárom ,,trükköt’’ beveti: <strong>medián abszolút eltérés</strong>, jele <span class="math inline">\(MAD\)</span>, tehát
<span class="math display">\[
    MAD=\mathrm{Me}\left(\left|x_i-\mathrm{Me}\left(x\right)\right|\right).
\]</span>
(A szakirodalom itt nem teljesen egyértelmű: néha <span class="math inline">\(MAD\)</span>-nak nevezik azt a mutatót is, ahol csak az első javítást csinálják meg, tehát abszolútértéket vesznek, de azokat továbbra is csak átlagolják, és az eltéréseket is az átlagtól veszik.)</p>
<p>A születési tömegek medián abszolút eltérése 563 gramm, tehát az újszülöttek testtömegeinek mediánjuk körül vett (abszolút) ingadozásának mediánja 563 gramm.</p>
</div>
<div id="deskriptivmennyegyvaltanalitikusmutatoszamokalakmutatok" class="section level5">
<h5><span class="header-section-number">3.4.1.2.3</span> Alakmutatók</h5>
<p>A fenti két jellemzőn túlmenően néha egyéb, még inkább részletekbe menő jellemzőit is használják egy változó leírásának. Egy tipikus példa erre a <strong>szimmetria</strong>: egy eloszlás szimmetrikus, ha a centrális tendencia helyétől mindkét irányban nagyjából hasonló a lefutása. (Vegyük észre, hogy ez nem következik még abból sem, ha két változóra ugyanaz a centrális tendencia, és ugyanaz a szóródás: ettől még az egyik lehet szimmetrikus, míg a másik nem.) A nem szimmetrikus eloszlásokat szokás <strong>ferde</strong> eloszlásoknak is nevezni; ezen belül is szoktak balra ferde (jobbra hosszan elnyúló) és jobbra ferde (balra hosszan elnyúló) eloszlásról beszélni, attól függően, hogy melyik irányban nagyobb a szóródás. További kérdések is felmerülnek, mint a csúcsosság, a multimodalitás stb. – ezekkel és a továbbiakkal azonban részletesen itt nem foglalkozunk.</p>
</div>
</div>
</div>
<div id="deskriptivmennyegyvaltgrafikus" class="section level3">
<h3><span class="header-section-number">3.4.2</span> Grafikus eszközök</h3>
<p>A grafikus eszközök közül először a hisztogramot, utána röviden a magfüggvényes sűrűségbecslőt, majd végül a boxplotot tárgyaljuk meg.</p>
<div id="deskriptivmennyegyvaltgrafikushisztogram" class="section level4">
<h4><span class="header-section-number">3.4.2.1</span> Hisztogram</h4>
<p>A hisztogram leegyszerűsítve nem más, mint az osztályközös gyakorisági sor ábrázolása oszlopdiagramon, annyi specialitással, hogy az oszlopokat közvetlenül egymás mellé rajzoljuk, hely kihagyása nélkül (<a href="deskriptiv.html#fig:hisztogram">3.2</a>. ábra).</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" title="1"><span class="kw">hist</span>(birthwt<span class="op">$</span>bwt, <span class="dt">xlab =</span> <span class="st">&quot;Születési tömeg [g]&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Gyakoriság [fő]&quot;</span>, <span class="dt">main =</span> <span class="st">&quot;&quot;</span>)</a>
<a class="sourceLine" id="cb14-2" title="2"><span class="kw">rug</span>(birthwt<span class="op">$</span>bwt)</a></code></pre></div>
<div class="figure"><span id="fig:hisztogram"></span>
<img src="bevbiostat_files/figure-html/hisztogram-1.png" alt="Példa egy mennyiségi változó ábrázolására hisztogrammal." width="672" />
<p class="caption">
Figure 3.2: Példa egy mennyiségi változó ábrázolására hisztogrammal.
</p>
</div>
<p>Az ábrán látható, hogy az oszlopok határai kijelölik az osztályközöket (ezek természetesen nem feltétlenül azonos szélességűek); adott osztályköz fölé pedig
<span class="math display">\[
    \frac{f_i}{n \cdot h_i}
\]</span>
magasságú oszlopokat rajzolunk, ahol <span class="math inline">\(h_i\)</span> az adott osztályköz szélessége. Ezen az ábrán feltüntettük (alul, apró tüskékként) magukat a nyers megfigyeléseket is (,,rugplot’’).</p>
<p>A hisztogram a legnépszerűbb adatvizualizációs módszer mennyiségi változókra. Ahogy már utaltunk is rá, hatalmas előnye, hogy a vizuálisan közölt információ rendkívül jól feldolgozható az emberi agy számára: a fenti hisztogram alapján szinte ,,ránézésre’’, egyetlen pillantással jó képünk alakul ki a centrális tendenciáról, a szóródásról, sőt, az eloszlás alakjának finomabb jellemzőiről is. Egy átlagot még el sem olvastunk, amikorra a hisztogram alapján már olyan finom jellemzőkről, mint az eloszlás szimmetriája is képünk van.</p>
<p>Hátránya, hogy kevésbé objektív (mint a grafikus módszerek általában) – ha például két változót össze kell hasonlítanunk, akkor két átlaggal (azaz két számmal) az értelemszerűen könnyebben megtehető mint két hisztogrammal.</p>
<p>A legnagyobb kihívás azonban az osztályközök helyes megválasztása. Ez a probléma teljesen ugyanaz, mint amit az osztályközös gyakorisági sornál is kifejtettünk. Sőt, itt talán még jobban szemléltethető: a <a href="deskriptiv.html#fig:hisztogramvalasztasok">3.3</a>. ábrán ugyanazt az adatsort ábrázoltuk, csak épp az optimálisnál lényegesen több, illetve lényegesen kevesebb osztályközt használva is.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" title="1"><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">3</span>))</a>
<a class="sourceLine" id="cb15-2" title="2"><span class="kw">hist</span>(birthwt<span class="op">$</span>bwt, <span class="dv">3</span>, <span class="dt">xlab =</span> <span class="st">&quot;Születési tömeg [g]&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Gyakoriság&quot;</span>, <span class="dt">main =</span> <span class="st">&quot;&quot;</span>)</a>
<a class="sourceLine" id="cb15-3" title="3"><span class="kw">hist</span>(birthwt<span class="op">$</span>bwt, <span class="dt">xlab =</span> <span class="st">&quot;Születési tömeg [g]&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Gyakoriság&quot;</span>, <span class="dt">main =</span> <span class="st">&quot;&quot;</span>)</a>
<a class="sourceLine" id="cb15-4" title="4"><span class="kw">hist</span>(birthwt<span class="op">$</span>bwt, <span class="dv">30</span>, <span class="dt">xlab =</span> <span class="st">&quot;Születési tömeg [g]&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Gyakoriság&quot;</span>, <span class="dt">main =</span> <span class="st">&quot;&quot;</span>)</a></code></pre></div>
<div class="figure"><span id="fig:hisztogramvalasztasok"></span>
<img src="bevbiostat_files/figure-html/hisztogramvalasztasok-1.png" alt="Ugyanazon adatsor ábrázolása különféle számú osztályközt tartalmazó hisztogrammal." width="672" />
<p class="caption">
Figure 3.3: Ugyanazon adatsor ábrázolása különféle számú osztályközt tartalmazó hisztogrammal.
</p>
</div>
<p>Itt érzékelhető igazán, hogy miért probléma az is, ha túl finom, és az is, ha túl durva felosztást választunk (adott, rögzített mintanagyság mellett!). Amennyiben az osztályközök száma túl kevés, akkor sok információt vesztünk: az eloszlásról kapott kép összemossa a finomabb részleteket (bal oldal). Úgy is szokták mondani: nagy lesz a torzítás. Ha viszont túl sok osztályközt választunk, akkor rendkívül esetlegessé válik, hogy egy osztályközbe hány mintaelem esik, nagyon ingadozó lesz a magasság (jobb oldal), úgy szokták mondani: nagy lesz a variancia. (Ez itt a sok más helyen is megjelenő torzítás-variancia trade-off egy példája.) Ahogy sokszor elmondtuk: valamiféle optimumot kell találni a kettő között. Ennek módszereiről az osztályközös gyakorisági sornál már írtunk.</p>
<p>Az osztályközöket többféleképp is megadhatjuk R-ben:</p>
<ol style="list-style-type: decimal">
<li>Explicite megadjuk az osztályközök határait: <code>hist( birthwt$bwt, breaks = c( 500, 1500, 2000, 2500, 2750, 3000, 3250, 3500, 5000 ) )</code>.</li>
<li>Megadjuk az osztályközök számát: <code>hist( birthwt$bwt, breaks = 10 )</code>.</li>
<li>Megadjuk a szabály nevét, amivel kérjük az osztályközök számának kiszámolását: <code>hist( birthwt$bwt, breaks = "Sturges" )</code>.</li>
<li>Saját függvényt adunk meg, mely vagy az osztályközök számát, vagy a határait kiszámolja az adatok alapján.</li>
</ol>
</div>
<div id="deskriptivmennyegyvaltgrafikuskde" class="section level4">
<h4><span class="header-section-number">3.4.2.2</span> Magfüggvényes sűrűségbecslő</h4>
<p>A hisztogrammal kapcsolatos egyik probléma az előbb említett érzékenység az osztályközök megválasztására. Emellett felvethető az is, hogy a hisztogram szakaszonként konstans becslést ad, ami zavaró lehet (különösen, ha kicsi a mintanagyság, és emiatt nem tudunk sok osztályközt felvenni). Ez utóbbit kiküszöböli, és sok gyakorlati esetben az előbbit is enyhíti a <strong>magfüggvényes sűrűségbecslő</strong> alkalmazása. Ennek matematikai részleteivel most nem foglalkozunk, megelégszünk annyival, hogy a hisztogramhoz hasonlóan az eloszlás alakját becsli, ám a hisztogramtól eltérően nem szakaszonként konstans görbével (<a href="deskriptiv.html#fig:kde">3.4</a>. ábra).</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" title="1"><span class="kw">plot</span>(<span class="kw">density</span>(birthwt<span class="op">$</span>bwt), <span class="dt">xlab =</span> <span class="st">&quot;Születési tömeg [g]&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Sűrűség&quot;</span>, <span class="dt">main =</span> <span class="st">&quot;&quot;</span>)</a></code></pre></div>
<div class="figure"><span id="fig:kde"></span>
<img src="bevbiostat_files/figure-html/kde-1.png" alt="Példa egy mennyiségi változó ábrázolására magfüggvényes sűrűségbecslővel." width="672" />
<p class="caption">
Figure 3.4: Példa egy mennyiségi változó ábrázolására magfüggvényes sűrűségbecslővel.
</p>
</div>
<p>Sajnos az osztályközök megválasztásának problémája teljesen nem oldódik meg, a magfüggvényes sűrűségbecslőnek is van ugyanis állítható paramétere (magfüggvény, és különösen az ún. sávszélesség). Ennek optimális megválasztása szintén probléma lehet, különösen, ha nagyon egyenetlen a mintaelemek eloszlása.</p>
</div>
<div id="deskriptivmennyegyvaltgrafikusboxplot" class="section level4">
<h4><span class="header-section-number">3.4.2.3</span> (Tukey-féle) boxplot</h4>
<p>Végül egy egész más elven felépülő, de szellemes, és a gyakorlatban is nagyon hasznos vizualizációs módszerrel ismerkedünk meg, a (Tukey-féle)  (vagy ritkán használt magyar nevén: dobozábrával).</p>
<p>A boxplot nem más, mint egy számegyenes fölé rajzolt téglalap, mely egy adott változót reprezentál úgy, hogy a téglalap alsó széle az alsó kvartilisnél (<span class="math inline">\(Q_1\)</span>-nél), a felső széle pedig a felső kvartilisnél (<span class="math inline">\(Q_3\)</span>-nál) van. A téglalapon belül egy vastagabb függőleges vonal is látható, ez a mediánnál található (<a href="deskriptiv.html#fig:boxplot">3.5</a>. ábra).</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" title="1"><span class="kw">boxplot</span>(birthwt<span class="op">$</span>bwt)</a></code></pre></div>
<div class="figure"><span id="fig:boxplot"></span>
<img src="bevbiostat_files/figure-html/boxplot-1.png" alt="Példa egy mennyiségi változó ábrázolására boxplottal." width="672" />
<p class="caption">
Figure 3.5: Példa egy mennyiségi változó ábrázolására boxplottal.
</p>
</div>
<p>A boxplotból két ,,antenna’’ nyúlik ki felfelé és lefelé. A boxplot alapváltozatában ezek a mintaminimumig és mintamaximumig nyúlnak ki, de a némileg haladóbb megvalósításban (amit a fenti ábra is mutat) az alsó antenna nem a minimumig terjed, hanem a legkisebb elemig, ami nem kisebb, mint <span class="math inline">\(\mathrm{Me}-\alpha \cdot IQR\)</span>; hasonlóképp a felső antenna nem a maximumig terjed, hanem a legnagyobb elemig, ami nem nagyobb mint <span class="math inline">\(\mathrm{Me}+\alpha \cdot IQR\)</span>. (<span class="math inline">\(\alpha\)</span> egy előre megadott konstans, tipikusan <span class="math inline">\(\alpha=1,\!5\)</span>.) Azokat az elemeket melyek ezen kívül helyezkednek el, külön szimbólum, például kis karika jelöli. E mögött az a megfontolás, hogy így a boxplot egyszerű outlier-szűrést is lehetővé tesz: azok az elemek minősülnek outliernek, melyek az antennákon kívül helyezkednek el.</p>
<p>A boxplot jóval nagyobb információtömörítést hajt végre mint akár a hisztogram, akár a magfüggvényes becslő – ez részint hátránya, bár ennek ellenére gyakorlott szem számára így is meglehetősen jó információt hordoz az eloszlás alakjáról. Azonban ugyanez előnye is, hiszen kompakt (ami különösen jól jön akkor, ha például több csoportot kell összehasonlítani), valamint további nagy előnye, hogy – szemben mind a hisztogrammal, mind a magfüggvényes becslővel – semmilyen paraméter hangolását nem igényli, így kinézete teljesen egyértelműen meghatározott.</p>
</div>
</div>
</div>
<div id="deskriptivminketvalt" class="section level2">
<h2><span class="header-section-number">3.5</span> Minőségi változók kétváltozós elemzése</h2>
<p>Minőségi változók kapcsolatát <strong>asszociációnak</strong> szokás nevezni a statisztikában. Erre jó példa adatbázisunk rassz (<code>race</code>) és irritábilis méh (<code>ui</code>) változói, mely az alany rassz szerinti hovatartozását és az irritábilis méh szindróma fennállását adja meg.</p>
<div id="deskriptivminketvaltanalitikus" class="section level3">
<h3><span class="header-section-number">3.5.1</span> Analitikus eszközök</h3>
<p>Ahogy már megbeszéltük, a kétváltozós vizsgálatok sava-borsa az lesz, hogy a változók <em>kapcsolatáról</em> is képesek leszünk nyilatkozni. Ahhoz, hogy precízen definiáljuk, hogy mit értünk kapcsolat alatt, elsőként bemutatjuk az <strong>kontingenciatáblát</strong> (vagy kombinációs táblát vagy kereszttáblát), mely egyúttal az egyik legfontosabb analitikus eszköz is lesz két minőségi változó kapcsolatának vizsgálatában. Ezt követően nagyon röviden beszélünk a kapcsolat jellemzésére használható mutatószámokról is.</p>
<div id="deskriptivminketvaltanalitikuskontingenciatabla" class="section level4">
<h4><span class="header-section-number">3.5.1.1</span> Kontingenciatábla</h4>
<p>A kontingenciatábla egy olyan táblázat, melynek soraiban és oszlopaiban a két változó lehetséges kimenetelei vannak, az egyes cellákban pedig azon megfigyelési egységek darabszáma (tehát gyakorisága), melyek a cella sora és oszlopa szerinti kimenetűek a sorhoz illetve az oszlophoz rendelt változó szerint. Például, a rassz és az irritábilis méh kontingenciatáblája így néz ki:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" title="1"><span class="kw">table</span>(birthwt<span class="op">$</span>race, birthwt<span class="op">$</span>ui)</a></code></pre></div>
<pre><code>##               
##                 0  1
##   Kaukázusi    83 13
##   Afroamerikai 23  3
##   Egyéb        55 12</code></pre>
<p>Tehát például 83 olyan megfigyelési egység van az adatbázisban, ahol az anya rassza kaukázusi <em>és</em> nincs irritábilis méh szindrómája 12 egyéb rasszú, és irritábilis méh szindrómában szenvedő alany van, és így tovább.</p>
<p>A kontingenciatábla szigorúan véve csak a <span class="math inline">\(3 \times 2\)</span> darab gyakoriságot jelenti; de néha összegző sorokat vagy oszlopokat írunk mellé:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" title="1">tab &lt;-<span class="st"> </span><span class="kw">table</span>(birthwt<span class="op">$</span>race, birthwt<span class="op">$</span>ui)</a>
<a class="sourceLine" id="cb20-2" title="2"><span class="kw">rbind</span>(<span class="kw">cbind</span>(tab, <span class="kw">margin.table</span>(tab, <span class="dv">1</span>)), <span class="kw">cbind</span>(<span class="kw">t</span>(<span class="kw">margin.table</span>(tab, <span class="dv">2</span>)), <span class="kw">margin.table</span>(tab)))</a></code></pre></div>
<pre><code>##                0  1    
## Kaukázusi     83 13  96
## Afroamerikai  23  3  26
## Egyéb         55 12  67
##              161 28 189</code></pre>
<p>Ezek neve: <strong>perem- vagy vetületi gyakoriság</strong>. (Mindkét elnevezés logikus: perem, hiszen a kontingenciatábla peremére kell ezeket ráírni, és vetületi, hiszen úgy kaphatjuk, hogy a kontingenciatáblát levetítjük vízszintesen vagy függőlegesen ,,levetítjük’‘, vetítés alatt most azt értve, hogy az egymásra ,,vetülő’’ elemeket összeadjuk.) A 189 a mintanagyság.</p>
<p>A fenti gyakoriságokon túl természetesen relatív gyakoriságokról is beszélhetünk. A relatív gyakoriság definícióját közvetlenül alkalmazva kapjuk azt a lehetőséget, hogy mindegyik cellát leosztjuk a mintanagysággal, például a bal felső <span class="math inline">\(83/189=43,\!9\)</span>% lesz. Ez az irritábilis méh szindrómában szenvedő kaukázusiak aránya a teljes mintán belül. A relatív gyakoriságokkal kitöltött kontingenciatábla peremei a <strong>relatív peremgyakoriságok</strong> (vagy relatív vetületi gyakoriságok). Szokás ezt <strong>peremmegoszlásnak</strong> vagy <strong>vetületi megoszlásnak</strong> is nevezni. (Az elnevezés nem meglepő: már korábban is utaltunk rá, hogy egy teljes relatív gyakorisági sort a statisztikusok általában megoszlásnak neveznek.)</p>
<p>Kontingenciatábla esetén azonban van egy másik – logikus – mód arra, hogy relatív gyakoriságot értelmezzünk: a 43,9% megadja, hogy az összes alany mekkora hányada kaukázusi  irritábilis méh szindrómában nem szenvedő, de minket érdekelhet az is, hogy az (összes helyett) csak az irritábilis méh szindrómában nem szenvedők mekkora hányada kaukázusi. Azaz: a 83-at nem a 189-cel, hanem a 161-gyel osztjuk le: <span class="math inline">\(83/161=51,\!6\)</span>%. Ezt nevezzük <strong>feltételes relatív gyakoriságnak</strong>. Azért feltételes, mert ez egy relatív gyakoriság <em>azon feltétel mellett</em>, hogy valaki nem szenved irritábilis méh szindrómában. Más szóval: ha <em>feltesszük</em>, hogy az alanyaink nem szenvednek irritábilis méh szindrómában akkor közöttük 51,6% a kaukázusiak aránya. Ez természetesen kiszámolható a rassz változó másik két kimenetére is; az így kapott 51,6%–14,3%–34,2% egy teljes (csak épp feltételes) relatív gyakorisági sor, összege nyilván 100%. Szokás ezt a sorváltozó (esetünkben a rassz) <strong>feltételes megoszlásának</strong> is nevezni, az a oszlopváltozó (esetünkben az irritábilis méh) <em>adott értéke</em> (esetünkben: ‘igen’) mint feltétel mellett. Természetesen ugyanezek kiszámolhatóak a jobb oldali oszlopra is, ez magyarul azt jelenti, hogy az irritábilis méh ‘nem’ kimenetére feltételezünk. Az eljárás ugyanez, azzal a különbséggel, hogy a jobb oldali számokat nyilván 28-cal kell leosztani. A feltételes relatív gyakoriság tehát nem más, mint a gyakoriság adott peremgyakorisággal osztva.</p>
<p>Természetesen nem csak az oszlopváltozóra feltételezhetünk! Pontosan ugyanígy van értelme beszélni az oszlopváltozó feltételes eloszlásáról a sorváltozó adott értéke, mint feltétel mellett. Például kijelenthetjük, hogy annak feltételes relatív gyakorisága, hogy egy alany nem szenved irritábilis méh szindrómában <span class="math inline">\(83/96=86,\!5\)</span>% <em>azon feltétel mellett</em>, hogy kaukázusi a rassza. Hasonlóan továbbmenve azt is mondhatjuk, hogy az irritábilis méh fennállásának feltételes megoszlása azon feltétel mellett, hogy az alany kaukázusi, 86,5%–13,5%.</p>
<p>Összefoglalva, egy cellához négyféle számot is rendelhetünk, a bal felső példáján: 83 (gyakoriság), 43,9% (relatív gyakoriság), 51,6% (feltételes relatív gyakoriság azon feltétel mellett, hogy nem áll fenn irritábilis méh szindróma) és 86,5% (feltételes relatív gyakoriság azon feltétel mellett, hogy a rassz kaukázusi). Mindezeket szemléltetik a következő táblázatok.</p>
<p>Relatív gyakoriságok (peremeken a vetületi megoszlásokkal):</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" title="1">tab &lt;-<span class="st"> </span><span class="kw">prop.table</span>(<span class="kw">table</span>(birthwt<span class="op">$</span>race, birthwt<span class="op">$</span>ui))</a>
<a class="sourceLine" id="cb22-2" title="2"><span class="kw">rbind</span>(<span class="kw">cbind</span>(tab, <span class="kw">margin.table</span>(tab, <span class="dv">1</span>)), <span class="kw">cbind</span>(<span class="kw">t</span>(<span class="kw">margin.table</span>(tab, <span class="dv">2</span>)), <span class="kw">margin.table</span>(tab)))</a></code></pre></div>
<pre><code>##                0    1    
## Kaukázusi    0.4 0.07 0.5
## Afroamerikai 0.1 0.02 0.1
## Egyéb        0.3 0.06 0.4
##              0.9 0.15 1.0</code></pre>
<p>Irritábilis méh feltételes relatív gyakoriságai a rassz különböző kimenetei, mint feltétel esetén</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" title="1">tab &lt;-<span class="st"> </span><span class="kw">prop.table</span>(<span class="kw">table</span>(birthwt<span class="op">$</span>race, birthwt<span class="op">$</span>ui), <span class="dv">1</span>)</a>
<a class="sourceLine" id="cb24-2" title="2"><span class="kw">rbind</span>(<span class="kw">cbind</span>(tab, <span class="kw">margin.table</span>(tab, <span class="dv">1</span>)))</a></code></pre></div>
<pre><code>##                0   1  
## Kaukázusi    0.9 0.1 1
## Afroamerikai 0.9 0.1 1
## Egyéb        0.8 0.2 1</code></pre>
<p>Rassz feltételes relatív gyakoriságai az irritábilis méh különböző kimenetei, mint feltétel esetén:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" title="1">tab &lt;-<span class="st"> </span><span class="kw">prop.table</span>(<span class="kw">table</span>(birthwt<span class="op">$</span>race, birthwt<span class="op">$</span>ui), <span class="dv">2</span>)</a>
<a class="sourceLine" id="cb26-2" title="2"><span class="kw">rbind</span>(tab, <span class="kw">t</span>(<span class="kw">margin.table</span>(tab, <span class="dv">2</span>)))</a></code></pre></div>
<pre><code>##                0   1
## Kaukázusi    0.5 0.5
## Afroamerikai 0.1 0.1
## Egyéb        0.3 0.4
##              1.0 1.0</code></pre>
<p>Természetesen nem arról van szó, hogy bármelyik jobb lenne, mint a többi – egyszerűen más elemzési célra alkalmasak. A feltételes megoszlásokra gondolva, az is érdekes kérdés lehet, hogy a kaukázusiak mekkora hányada szenved irritábilis méh szindrómában, és az is érdekes (de más tartalmú) kérdés, hogy az irritábilis méh szindrómában szenvedők mekkora hányada kaukázusi rasszú. Mindezek között egyszerű algebrai összefüggések állnak fenn, ezeket most nem részletezzük.</p>
<p>Továbbhaladva, tökéletesen látható, hogy miért mondtuk, hogy a többváltozós elemzés az egyváltozós elemzések kiterjesztése: a fenti kétdimenziós kontingenciatáblában <em>minden</em> információ benne van, amit a két változót külön-külön elemezve látnánk: egyszerűen levetítjük a kontingenciatáblát a megfelelő dimenziós mentén és kapott vetületi gyakoriságok nem mások lesznek, mint a vetítési irány változójának gyakorisági sora! (Amiben minden információ benne van.)</p>
<p>Az tehát egyértelmű, hogy ez tartalmazza mindazt az információt, amit a két változó külön-külön végzett vizsgálata – csakhogy mi azt állítottuk, hogy többet is. Ez vezet el a változók kapcsolatának kérdéséhez. Minőségi változók esetében (kontingenciatáblán) akkor mondjuk, hogy két változó kapcsolatban van egymással, ha a sorváltozó feltételes megoszlásai <em>ugyanazok</em>, az oszlopváltozó <em>bármely</em> értékére is feltételezünk. Vagy – ami ezzel egyenértékű –: az oszlopváltozó feltételes megoszlásai <em>ugyanazok</em>, a sorváltozó <em>bármely</em> értékére is feltételezünk. (Ez első ránézésre, kicsit nagyvonalú volt, de belátható matematikailag, hogy a kettő valóban egyenértékű: ha az oszlopváltozó feltételes megoszlásai ugyanazok minden sorban, akkor a sorváltozó feltételes megoszlásai is ugyanazok minden oszlopban, és fordítva is, ha az oszlopváltozó feltételes megoszlásai nem ugyanazok minden sorban, akkor a sorváltozó feltételes megoszlásai sem ugyanazok minden oszlopban.)</p>
<p>Ez a definíció jogos: általánosságban véve is, az, hogy két változó között nincs kapcsolat, azt jelenti statisztikai nyelven, hogy az egyikre vonatkozó információból nem nyerünk információt a másikra vonatkozóan. Így már érthető ez a kontingenciatáblákra alkalmazott definíció: ha nincs kapcsolat, akkor hiába mondjak meg valaki, hogy mi – például – a sorváltozó értéke, ebből semmit nem tudunk meg az oszlopváltozó feltételes megoszlásáról (hiszen az minden sorban ugyanaz!). Ha van kapcsolat, akkor nyerünk plusz-információt (hiszen más lesz a feltételes megoszlása).</p>
<p>Látható, hogy ebben az esetben csak nagyon gyenge kapcsolatról beszélhetünk: a sorváltozó feltételes megoszlása mindkét oszlopban (precízen: az oszlopváltozó mindkét kimenetére feltételezve) nagyjából ugyanaz (kb. 50%–kb. 10%–kb. 40%), és az oszlopváltozó feltételes megoszlása is nagyjából ugyanaz mindhárom sorban (kb. 85%–kb. 15%). Ahogy már elmondtuk, az előbbi mondat bármelyik feléből automatikusan következik a másik fele. Itt tehát szemléletesen is látható a kapcsolat hiányának tartalma: <em>hiába is</em> mondja meg valaki, hogy az alany rassza kaukázusi, afroamerikai vagy egyéb, szinte <em>ugyanúgy</em> csak azt tudjuk mondani, hogy ,,akkor 85%–15% a megoszlás az irritábilis méh fennállása szerint’’. A rasszra vonatkozó információ nem adott szinte semmilyen információt a másik változóról.</p>
<p>Képzeljünk el ezzel szemben – másik végletként – egy olyan esetet, melyben a 189 alany közül 100 kaukázusi irritábilis méh szindróma nélkül, és 89 egyéb rasszú irritábilis méh szindrómával! Ebben az esetben az egyik változóra vonatkozó információ nem egyszerűen ,,elárul valamit’’ a másik változóról, hanem egyenesen determinálja azt: ha valaki elárulja, hogy egy alany kaukázusi rasszú, akkor <em>biztosan tudjuk</em>, hogy nem szenved irritábilis bél szindrómában, ha pedig azt mondja, hogy egyéb rasszú, akkor rögtön tudjuk, hogy szenved ebben. (Természetesen itt is igaz, hogy a dolog fordítva is működik: ha tudjuk, hogy egy alany nem szenved irritábilis méh szindrómában, akkor azonnal tudjuk, hogy kaukázusi, ha pedig nem szenved ebben, akkor biztos, hogy egyéb rasszú.) Ez a kapcsolat másik végpontja.</p>
<p>Zárásként megjegyezzük, hogy a statisztikában valójában nem így szokták bevezetni a kapcsolat fogalmát, hanem úgy, mint azt az esetet, amikor a két változó nem független egymástól; függetlenség alatt pedig azt értik, hogy az együttes megoszlás a vetületi megoszlások szorzataként áll elő. Érdemes végiggondolni, hogy ez valóban egybeesik a hétköznapi ,,függetlenség’’ fogalommal. Szintén érdemes végiggondolni, hogy ebből valóban következik a fenti definíció, de ezzel részletesebben nem foglalkozunk most.</p>
</div>
<div id="deskriptivminketvaltanalitikusmutatoszamok" class="section level4">
<h4><span class="header-section-number">3.5.1.2</span> Mutatószámok</h4>
<p>A kapcsolat <em>erősségének</em> kvalitatív fogalmát fent megadtuk; erre több mutatót is definiáltak, melyekkel az erősség számszerűen is lemérhető. Amennyiben a változók nominálisak, úgy pusztán erre van lehetőség.</p>
<p>Ha azonban a változók ordinálisak, úgy értelmet nyert a kapcsolat <em>irányának</em> fogalma is. Ordinális változók esetén ugyanis a sorok és oszlopok sorrendje nem tetszőleges, van értelme mindkét változó szerint ,,nagyobb’’ és ,,kisebb’’ kimenetről beszélni. Innentől kezdve tehát nem csak azt mondhatjuk, hogy van kapcsolat, ha más oszlopban más a feltételes megoszlás, hanem értelmet nyer az a kijelentés is, hogy nagyobb oszlopban a feltételes megoszlás úgy más, hogy inkább nagyobb sorbeli érték szerepelnek, vagy épp úgy, hogy inkább kisebbek. (Itt is egyenértékű, ha ugyanezt a sorok és oszlopok fordított szerepével mondjuk el.) Ezt ragadja meg a kapcsolat irányának fogalma: ha van kapcsolat (nem 0 az erőssége), akkor az pozitív, amennyiben az oszlopváltozó szerinti nagyobb érték tendenciájában a sorváltozó szerinti nagyobb értékkel jár együtt (és fordítva), negatív, ha az oszlopváltozó szerinti nagyobb érték tendenciájában a sorváltozó szerint kisebb értékkel jár együtt (és fordítva). Ordinális változónál erről is lehet nyilatkozni mutatókkal.</p>
<p>A konkrét mutatószámokkal most nem foglalkozunk (többek között azért sem, mert meglehetősen sok van belőlük, attól függően, hogy pontosan hogyan viselkednek az egyes változók).</p>
</div>
</div>
<div id="deskriptivminketvaltgrafikus" class="section level3">
<h3><span class="header-section-number">3.5.2</span> Grafikus eszközök</h3>
<p>Kontingenciatáblát vizualizálni ún. mozaikábrával és asszociációs ábrával lehet, ezek azonban nem túl látványos, és emiatt nem is túl gyakran használt módszerek, így most mi sem részletezzük ezeket.</p>
<p>Ami bevettebb, az a vetületi megoszlások (vagy nevezetes feltételes megoszlások) ábrázolása egyszerűen oszlopdiagramon (vagy kördiagramon), ez azonban jól láthatóan ugyanaz a feladat, amit már minőségi változók egyváltozós elemzésénél megbeszéltünk.</p>
</div>
</div>
<div id="deskriptivmennyketvalt" class="section level2">
<h2><span class="header-section-number">3.6</span> Mennyiségi változók kétváltozós elemzése</h2>
<p>Mennyiségi változók kapcsolatát <strong>korrelációnak</strong> szokás nevezni a statisztikában. Erre jó példa adatbázisunk anyai testtömeg (<code>lwt</code>) és újszülött születési tömege (<code>bwt</code>) változói, melyek az anya illetve az újszülött testtömegét tartalmazzák.</p>
<div id="deskriptivmennyketvaltanalitikus" class="section level3">
<h3><span class="header-section-number">3.6.1</span> Analitikus eszközök</h3>
<p>A kapcsolat fogalmát mennyiségi változókra is ugyanazon gondolatot követve értelmezzük, mint amit minőségi változóknál már láttunk. Azt mondjuk, hogy két változó kapcsolatban van egymással, ha az egyik változó átlag feletti értékei tendenciájában a másik változó átlag feletti értékeivel járnak együtt (és ekkor persze fordítva is: az egyik változó átlag alatti értékei tendenciájában a másik változó átlag alatti értékeivel járnak együtt). Azaz: ha egy megfigyelési egység értéke az egyik változó szerint átlag feletti, akkor várhatóan a másik változó szerint is átlag feletti lesz. Pontosabban szólva ez a <em>pozitív</em> kapcsolat definíciója, a negatív esetén az egyik változó átlag feletti értékei tendenciájában a másik átlag alatti értékeivel járnak együtt, és fordítva. Itt természetesen <em>sztochasztikus</em> kapcsolatról beszélünk, ezért a ,,tendenciájában’’ kifejezés: nem arról van szó, hogy ha a megfigyelési egység egyik változója átlag feletti, akkor _biztos, hogy a másik is, de az esetek <em>többségében</em> érvényesül ez a tendencia.</p>
<p>Érdemes megfigyelni, hogy itt mindenképp van értelme az iránynak (összhangban azzal, hogy a mennyiségi változók bírnak az ordinális tulajdonságaival is, természetesen).</p>
<p>Két mennyiségi változó fent definiált kapcsolatát klasszikusan a <strong>kovarianciával</strong> szokás lemérni. Ennek definíciója:
<span class="math display">\[
    \mathrm{cov}\left(x,y\right)=\frac{\sum_{i=1}^n \left[\left(x_i-\overline{x}\right)\left(y_i-\overline{y}\right)\right]}{n}.
\]</span>
A számítás logikája vegytisztán tükrözi a definíciót: az <span class="math inline">\(\left(x_i-\overline{x}\right)\)</span> tükrözi az egyik, az <span class="math inline">\(\left(y_i-\overline{y}\right)\)</span> a másik változó szerint azt, hogy az adott megfigyelési egység átlag alatti vagy átlag feletti. Vegyük észre, hogy a kettő szorzata pedig <em>pontosan akkor</em> lesz pozitív, ha vagy mindkét változó szerint átlag feletti a megfigyelési egység, vagy mindkét változó szerint átlag alatti – azaz ha az adott megfigyelési egység a pozitív kapcsolatot erősíti meg! Ha a szorzat negatív, akkor az adott megfigyelési egység a negatív kapcsolatot erősíti.</p>
<p>Sőt, ennél több is igaz: a szorzatnak nem csak az előjele stimmel, de a nagysága is, az ugyanis kifejezi, hogy mennyire erősít meg bennünket az adott megfigyelési egység a kapcsolat fennállásában. Ha a megfigyelési egység egyik (pláne ha mindkét) változó szerint közel van az átlaghoz, akkor az csak gyenge ,,bizonyíték’’ a kapcsolat mellett (kis módosulással lehet, hogy az ellenkező irányú kapcsolatot erősítené), viszont ha mindkét változó szerint távol van az átlagtól, az erős érv a kapcsolat mellett.</p>
<p>A szummázás ezeket a hatásokat fogja összeadni megfigyelési egységről megfigyelési egységre, így előjele a kapcsolat irányát mutatja, abszolút értéke pedig annak erősségét. (Az <span class="math inline">\(n\)</span>-nel való leosztás nyilván szükséges, különben a kétszer megismételt adatbázison kétszer akkora lenne a kovariancia, holott az információ ugyanaz; tehát ezeket a szorzatokat átlagolni kell.)</p>
<p>Hogy mi a kovariancia problémája, az azonnal kiderül, ha közöljük az anyai és az újszülött testtömeg közti kovarianciát: 4141.7. Ami kétségtelenül kiolvasható ebből, hogy az anyai és az újszülött testtömeg között van kapcsolat, mégpedig pozitív irányú (nagyobb anyai tömeg – nagyobb újszülött tömeg, és fordítva), hiszen az előjel pozitív. Amiről viszont lényegében semmit nem tudunk meg, az az erősség! Annál is inkább, mert a kovariancia mértékegység-függő: más értéket kapunk, ha az újszülött testtömegét nem grammban, hanem kilogrammban rögzítjük. Tekintetbe véve, hogy az információ ettől még ugyanaz marad, ez nyilván nem szerencsés{} A probléma tehát, hogy honnan tudhatnánk, hogy a 4141.7 sok vagy kevés{}? Ebben segít minket az a matematikai észrevétel, hogy mindenképp fennáll a <span class="math inline">\(-s_x s_y \leq \mathrm{cov}\left(x,y\right) \leq s_x s_y\)</span> összefüggés, tehát a kovariancia abszolút értéke nem lehet nagyobb mint a két változó szórásának szorzata. Így máris van mihez viszonyítani a kovariancia nagyságát! Ez tehát a következő mutató definiálását adja, a neve <strong>korrelációs együttható</strong>:
<span class="math display">\[
    \mathrm{corr}\left(x,y\right)=\frac{\mathrm{cov}\left(x,y\right)}{s_x s_y}.
\]</span></p>
<p>Ez az előjel értelmezésén semmit nem változtat, hiszen a kovariancia előjelét meghagyja (a nevezőben szórások szerepelnek, így mindkettő szükségképp pozitív), viszont az abszolút értéket értelmezhetővé teszi, hiszen a korrelációra már az teljesül, hogy <span class="math inline">\(-1 \leq \mathrm{corr}\left(x,y\right) \leq 1\)</span>. A korreláció tehát minél közelebb van <span class="math inline">\(\pm 1\)</span>-hez, annál erősebb a két változó közötti kapcsolat.</p>
<p>Például, az anyai testtömeg és az újszülött születési tömege közti korrelációs együttható értéke 0.2. Ez alapján nem csak azt tudjuk mondani, hogy van kapcsolat és az pozitív irányú (a 0.2 előjele pozitív), de most már azt is, hogy ez a kapcsolat igen gyenge (ha elhelyezzük a 0.2-ot a 0–1 között).</p>
<p>Belátható, hogy az így definiált korrelációs együttható a <em>lineáris</em> kapcsolat erősségét méri (szokás emiatt lineáris korrelációs együtthatónak is nevezni). Valóban, ha a korreláció abszolút érték 1, az épp azt jelenti, hogy <span class="math inline">\(y=ax+b\)</span> függvényszerű kapcsolat van a két változó között. De általában is, a korreláció ,,erősségét’’ úgy kell érteni, hogy mennyire szorosan valósul meg ez az egyenesre illeszkedés. Fontos megjegyezni, hogy más kapcsolat erősségét <em>nem</em> méri ez az együttható, tehát nem lineáris kapcsolat lehet a két változó között (extrém esetben akár függvényszerű is!), úgy, hogy közben a lineáris korrelációs együttható értéke nulla.</p>
<p>Erre tekintettel szokás más korrelációs együtthatókat is definiálni, ezek közül megemlítjük a Spearman-<span class="math inline">\(\rho\)</span> és a Kendall-<span class="math inline">\(\tau\)</span> mutatókat, ezek ún. rangkorrelációs mutatók, amik nem konkrétan lineáris, hanem általános <em>monoton</em> kapcsolat erősségét mérik. Nem foglalkozunk vele részletesen, de megemlítjük, hogy itt is igaz, hogy a kapcsolat erőssége azzal van összefüggésben, hogy az egyik változó ismerete mennyi információt árul el a másik változóról (természetesen sztochasztikus értelemben).</p>
<p>Végül egy figyelmeztetés. Mint általában, természetesen itt is elmondható, hogy a mutatószám használata nagyon nagy információtömörítést jelent. Éppen ezért ne támaszkodjunk önmagában egy korrelációs együtthatóra (és különösen ne önmagában egy lineáris korrelációs együtthatóra) két változó kapcsolatának megítéléséhez, hiszen ez elfedi az esetleges nemlineáris kapcsolatokat, az outliereket stb. Erre egy nevezetes példa az Anscombe-kvartett, amit mi is hamarosan bemutatunk.</p>
</div>
<div id="deskriptivmennyketvaltvaltgrafikus" class="section level3">
<h3><span class="header-section-number">3.6.2</span> Grafikus eszközök</h3>
<p>Két mennyiségi változó kapcsolatának legfontosabb ábrázolási eszköze az <strong>szóródási diagram</strong>. A szóródási diagramot úgy kapjuk, hogy minden megfigyelési egységnek egy pontot feleltetünk meg a síkban úgy, hogy a pont egyik koordinátája a megfigyelési egység egyik, a másik koordinátája a másik változó szerinti értéke. (Tehát lényegében a megfigyelési egységhez tartozó változókat koordinátáknak tekintjük, és ezeket mérjük fel egy kétdimenziós koordináta-rendszer két tengelyére.) Az anyai és újszülött testtömeg szóródási diagramját a <a href="deskriptiv.html#fig:scatterplot">3.6</a>. ábra mutatja.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb28-1" title="1"><span class="kw">plot</span>(bwt <span class="op">~</span><span class="st"> </span>lwt, <span class="dt">data =</span> birthwt, <span class="dt">xlab =</span> <span class="st">&quot;Anya testtömege (UM) [font]&quot;</span>, <span class="dt">ylab =</span> <span class="st">&quot;Születési tömeg [g]&quot;</span>)</a>
<a class="sourceLine" id="cb28-2" title="2"><span class="kw">abline</span>(<span class="dt">h =</span> <span class="kw">mean</span>(birthwt<span class="op">$</span>bwt), <span class="dt">v =</span> <span class="kw">mean</span>(birthwt<span class="op">$</span>lwt), <span class="dt">lty =</span> <span class="st">&quot;dashed&quot;</span>)</a>
<a class="sourceLine" id="cb28-3" title="3"><span class="kw">abline</span>(<span class="kw">lm</span>(bwt <span class="op">~</span><span class="st"> </span>lwt, <span class="dt">data =</span> birthwt), <span class="dt">lty =</span> <span class="st">&quot;dotted&quot;</span>)</a></code></pre></div>
<div class="figure"><span id="fig:scatterplot"></span>
<img src="bevbiostat_files/figure-html/scatterplot-1.png" alt="Két mennyiségi változó kapcsolatának ábrázolása szóródási diagrammal." width="672" />
<p class="caption">
Figure 3.6: Két mennyiségi változó kapcsolatának ábrázolása szóródási diagrammal.
</p>
</div>
<p>Az ábrán bejelöltük (szaggatott vonallal, a két tengellyel párhuzamosan) a két változó átlagát is.</p>
<p>Jól látható, immár grafikusan is, hogy mit értünk a két változó közötti kapcsolat fogalmán: a pontok tendenciájukban a szaggatott vonalak által kijelölt koordináta-rendszer jobb felső és bal alsó kvadránsában találhatóak (átlag feletti – átlag feletti és átlag alatti – átlag alatti zónák). Természetesen látszik az is, hogy a kapcsolat sztochasztikus, azaz van pont a több kvadránsban is (itt aztán pláne, hiszen a kapcsolat nem is túl erős). Ne feledjük azt sem, hogy nem csak a pontok darabszáma számít, hanem a konkrét helyzetük is (mennyire ,,erősíti meg’’ a kapcsolat fennállását).</p>
<p>Ráerősítve az előbb mondottakra, az ábrán behúztuk a pontokra legjobban illeszkedő egyenest is. Ahogy említettük, a kapcsolat ,,erőssége’’ egyúttal azt is jelenti, hogy a pontok mennyire szorosan illeszkednek a rájuk legjobban illeszkedő egyenesre (látható, hogy itt nem túl szorosan).</p>
<p>Mindezeket szemlélteti a <a href="deskriptiv.html#fig:corrdemo">3.7</a>. ábra is, mely különböző korrelációs együtthatójú kapcsolatokat (különböző előjelekkel és abszolút értékekkel, azaz különböző irányú és erősségű kapcsolatokat) mutat be példákkal.</p>
<div class="figure"><span id="fig:corrdemo"></span>
<img src="bevbiostat_files/figure-html/corrdemo-1.png" alt="Különféle korrelációs együtthatók szemléltetése." width="1920" />
<p class="caption">
Figure 3.7: Különféle korrelációs együtthatók szemléltetése.
</p>
</div>
<p>A grafikus ábrázolás előnye, hogy (szemben a korrelációs együtthatóval) nem okoz gondot semmilyen outlier, nemlineáris kapcsolat stb. – ezek mind láthatóak lesznek az ábrán. (Itt is hangsúlyosan él tehát Tukey már említett tanácsa{}) Erre mutat példát a nevezetes Anscombe-kvartett (<a href="deskriptiv.html#fig:anscombe">3.8</a>. ábra). Az ábrák négy kétváltozós adatsor szóródási diagramját mutatják. Mindegyiknek <em>hajszálpontosan ugyanaz</em> a korrelációs együtthatója (sőt, az átlaguk és a szórásuk is – így ugyanaz a rájuk legjobban illeszkedő egyenes is), mégis, a valós helyzet drámaian más. Outlierek, nemlineáris kapcsolatok vannak jelen. Ez azonban csak ábrázolás után derül ki, a korrelációs együttható használata mindezt teljesen elfedné!</p>
<div class="figure"><span id="fig:anscombe"></span>
<img src="bevbiostat_files/figure-html/anscombe-1.png" alt="Az Anscombe-kvartett." width="672" />
<p class="caption">
Figure 3.8: Az Anscombe-kvartett.
</p>
</div>
<p>Zárásként megjegyezzük, hogy ebben a grafikus ábrázolásban valóban nincsen semmilyen információtömörítés. Az is igaz, hogy a kétváltozós elemzés tartalmaz minden információt, amit a két egyváltozós elemzés: a pontokat levetítve valamelyik tengelyre, visszakapjuk az adott tengely változójának adatait; azokat csoportosítva (a tengelyt osztályközökre bontva) rögtön készíthető például hisztogram. Szemléletesen látszik azonban az is, hogy <em>pusztán</em> a hisztogramokból (tehát az egyváltozós adatokból) <em>lehetetlen</em> lenne nyilatkozni a két változó közti kapcsolatról. (Képzeljünk egy egy olyan esetet, melyben a változók között erős kapcsolat van, de úgy, hogy mindkét változó önmagában szimmetrikus. Ekkor nyugodtan tükrözhetnénk a szóródási diagramot bármelyik átlagot jelentő szaggatott vonalra, az egyváltozós adatok ugyanazok maradnának, noha kétváltozósan pont hogy megfordult a kapcsolat iránya.) Ezért több a kétváltozós elemzés mint két egyváltozós elemzés.</p>
</div>
</div>
<div id="deskriptivtovabbitobbvalt" class="section level2">
<h2><span class="header-section-number">3.7</span> További többváltozós elemzések</h2>
<p>A kétváltozós esetek tárgyalásából a fentiekben kimaradt az az eset, amikor egy minőségi és egy mennyiségi változó kapcsolatát kell vizsgálni. Ezt <em>vegyes kapcsolatnak</em> szokás nevezni; részletesebben most nem foglalkozunk vele.</p>
<p>A másik kérdés, ami felmerül, hogy mi a helyzet kettőnél több változó esetén. Ha nem lényegesen több változóról van szó, akkor a fenti módszerek – több-kevesebb módosítással – de kiterjeszthetőek. Például a szóródási diagram elvileg három változós esetre változatlanul kiterjeszthető (bár a gyakorlatban már ezt sem nagyon szokták használni, hiszen egy három dimenziós pontfelhő csak számítógépen tekinthető meg érdemben, és ott se túl áttekinthető emberi szemnek). Négy és annál több dimenziónál már trükkre van szükség; a tipikus megoldás, hogy minden lehetséges koordináta-párra levetítik a sokdimenziós pontfelhőt, és az így kapott kétdimenziós szóródási diagramokat mutatják meg (mátrix szóródási diagram). Egy-két tucat változó felett azonban már ez sem igazán tekinthető át, illetőleg már nem nevezhető érdemben kettőnél több dimenziós elemzésnek. Hasonló a helyzet a korrelációs együtthatóval, illetve a kontingenciatáblával és elemzési eszközeivel.</p>
<!-- Éppen ezért sokváltozós elemzésekhez már lényegesen eltérő módszerek alkalmazására is szükség lehet. Ilyenek -- csak említés szintjén -- a főkomponens-analízis, illetve a faktoranalízis, a klaszteranalízis vagy épp a többdimenziós skálázás (elsősorban mennyiségi változókhoz), és a korrespondenciaanalízis vagy a loglineáris modellezés (elsősorban minőségi változókhoz). -->
<!-- Bár meglehetősen más logikát követ, de idesorolható a többváltozós regresszió (gyakorlatban roppant fontosságú) eszköze is. -->

</div>
</div>
<!-- Default Statcounter code for Physcon Research
http://research.physcon.uni-obuda.hu/ -->
<script type="text/javascript">
var sc_project=11601191; 
var sc_invisible=1; 
var sc_security="5a06c22d"; 
</script>
<script type="text/javascript"
src="https://www.statcounter.com/counter/counter.js"
async></script>
<noscript><div class="statcounter"><a title="ingyen
webstatisztika" href="https://www.statcounter.hu/"
target="_blank"><img class="statcounter"
src="https://c.statcounter.com/11601191/0/5a06c22d/1/"
alt="ingyen webstatisztika"></a></div></noscript>
<!-- End of Statcounter Code -->
            </section>

          </div>
        </div>
      </div>
<a href="a-statisztika-alapjai.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="induktiv.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/tamas-ferenci/bevbiostat/edit/master/02-deskriptiv.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": ["bevbiostat.pdf", "bevbiostat.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
